package lt.vaeloria.ooc;

import java.text.Normalizer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Generated v0.9.1 catalog: 200 additional bundled, illustrated enemies. */
final class EnemyCatalogV091 {
    static final class Enemy {
        final String id, name, region, role, trait, description;
        final int danger, hp, attack, defense, speed, artwork;

        Enemy(String id, String name, String region, String role, String trait, String description,
              int danger, int hp, int attack, int defense, int speed, int artwork) {
            this.id = id;
            this.name = name;
            this.region = region;
            this.role = role;
            this.trait = trait;
            this.description = description;
            this.danger = danger;
            this.hp = hp;
            this.attack = attack;
            this.defense = defense;
            this.speed = speed;
            this.artwork = artwork;
        }
    }

    private static final String[] REGIONS = new String[]{"PELENŲ NEKROPOLIS", "KRAUJŠAKNĖS GIRIA", "GELEŽINĖS VIRŠŪNĖS", "MERIDIANO TUŠTUMA", "UŽMIRŠTOS DIRBTUVĖS", "BEDUGNĖS PAKRANTĖ", "AUDRŲ ŠIAURĖ", "LUMINAROS ŠEŠĖLIAI"};

    static final Enemy[] ALL = new Enemy[]{
            new Enemy("V091-001", "Pelenų skalikas", "PELENŲ NEKROPOLIS", "Medžiotojas", "pelenų šydas", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – pelenų šydas; kovoje jis veikia kaip medžiotojas.", 2, 144, 26, 23, 38, R.drawable.monster_v091_001),
            new Enemy("V091-002", "Anglies šmėkla", "PELENŲ NEKROPOLIS", "Persekiotojas", "nekrotinis atsparumas", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – nekrotinis atsparumas; kovoje jis veikia kaip persekiotojas.", 3, 197, 36, 32, 50, R.drawable.monster_v091_002),
            new Enemy("V091-003", "Apdegęs sargybinis", "PELENŲ NEKROPOLIS", "Sargas", "žarijų šuolis", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – žarijų šuolis; kovoje jis veikia kaip sargas.", 3, 208, 39, 35, 57, R.drawable.monster_v091_003),
            new Enemy("V091-004", "Kaulinė kapų žiurkė", "PELENŲ NEKROPOLIS", "Pasalūnas", "kapų grandinės", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – kapų grandinės; kovoje jis veikia kaip pasalūnas.", 4, 261, 49, 44, 52, R.drawable.monster_v091_004),
            new Enemy("V091-005", "Dūmų ragana", "PELENŲ NEKROPOLIS", "Ritualistas", "juodoji liepsna", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – juodoji liepsna; kovoje jis veikia kaip ritualistas.", 4, 272, 40, 32, 59, R.drawable.monster_v091_005),
            new Enemy("V091-006", "Kaulų piligrimas", "PELENŲ NEKROPOLIS", "Žvalgas", "pelenų šydas", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – pelenų šydas; kovoje jis veikia kaip žvalgas.", 4, 228, 43, 35, 49, R.drawable.monster_v091_006),
            new Enemy("V091-007", "Žarijų spektras", "PELENŲ NEKROPOLIS", "Naikintojas", "nekrotinis atsparumas", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – nekrotinis atsparumas; kovoje jis veikia kaip naikintojas.", 5, 281, 53, 44, 61, R.drawable.monster_v091_007),
            new Enemy("V091-008", "Pelenų riteris", "PELENŲ NEKROPOLIS", "Dvikovininkas", "žarijų šuolis", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – žarijų šuolis; kovoje jis veikia kaip dvikovininkas.", 5, 292, 56, 47, 68, R.drawable.monster_v091_008),
            new Enemy("V091-009", "Sarkofago mimikas", "PELENŲ NEKROPOLIS", "Spąstų kūrėjas", "kapų grandinės", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – kapų grandinės; kovoje jis veikia kaip spąstų kūrėjas.", 5, 303, 47, 50, 58, R.drawable.monster_v091_009),
            new Enemy("V091-010", "Suanglėjęs milžinas", "PELENŲ NEKROPOLIS", "Smogikas", "juodoji liepsna", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – juodoji liepsna; kovoje jis veikia kaip smogikas.", 6, 356, 57, 44, 70, R.drawable.monster_v091_010),
            new Enemy("V091-011", "Nekropolio varpo žvėris", "PELENŲ NEKROPOLIS", "Teritorijos sargas", "pelenų šydas", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – pelenų šydas; kovoje jis veikia kaip teritorijos sargas.", 5, 270, 53, 41, 55, R.drawable.monster_v091_011),
            new Enemy("V091-012", "Žarijų šikšnosparnių karalienė", "PELENŲ NEKROPOLIS", "Skrendantis medžiotojas", "nekrotinis atsparumas", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – nekrotinis atsparumas; kovoje jis veikia kaip skrendantis medžiotojas.", 6, 323, 63, 50, 67, R.drawable.monster_v091_012),
            new Enemy("V091-013", "Laidotuvių kandis", "PELENŲ NEKROPOLIS", "Silpnintojas", "žarijų šuolis", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – žarijų šuolis; kovoje jis veikia kaip silpnintojas.", 6, 334, 54, 53, 74, R.drawable.monster_v091_013),
            new Enemy("V091-014", "Lydytos kaukolės roplys", "PELENŲ NEKROPOLIS", "Pramušėjas", "kapų grandinės", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – kapų grandinės; kovoje jis veikia kaip pramušėjas.", 6, 345, 57, 56, 64, R.drawable.monster_v091_014),
            new Enemy("V091-015", "Kapų grandinių kalėtojas", "PELENŲ NEKROPOLIS", "Kontrolierius", "juodoji liepsna", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – juodoji liepsna; kovoje jis veikia kaip kontrolierius.", 7, 398, 67, 50, 76, R.drawable.monster_v091_015),
            new Enemy("V091-016", "Juodosios liepsnos kunigas", "PELENŲ NEKROPOLIS", "Burtininkas", "pelenų šydas", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – pelenų šydas; kovoje jis veikia kaip burtininkas.", 6, 312, 63, 47, 61, R.drawable.monster_v091_016),
            new Enemy("V091-017", "Kapinių kaulų elnias", "PELENŲ NEKROPOLIS", "Greitas puolėjas", "nekrotinis atsparumas", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – nekrotinis atsparumas; kovoje jis veikia kaip greitas puolėjas.", 7, 365, 61, 56, 73, R.drawable.monster_v091_017),
            new Enemy("V091-018", "Suodžių gargulis", "PELENŲ NEKROPOLIS", "Aukštumų sargas", "žarijų šuolis", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – žarijų šuolis; kovoje jis veikia kaip aukštumų sargas.", 7, 376, 64, 59, 63, R.drawable.monster_v091_018),
            new Enemy("V091-019", "Krematoriumo išsigimėlis", "PELENŲ NEKROPOLIS", "Minios laužytojas", "kapų grandinės", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – kapų grandinės; kovoje jis veikia kaip minios laužytojas.", 7, 387, 67, 62, 70, R.drawable.monster_v091_019),
            new Enemy("V091-020", "Pelenų skorpionas", "PELENŲ NEKROPOLIS", "Nuodytojas", "juodoji liepsna", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – juodoji liepsna; kovoje jis veikia kaip nuodytojas.", 8, 440, 77, 56, 82, R.drawable.monster_v091_020),
            new Enemy("V091-021", "Obsidiano karsto golemas", "PELENŲ NEKROPOLIS", "Elitinis sargas", "pelenų šydas", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – pelenų šydas; kovoje jis veikia kaip elitinis sargas.", 8, 396, 68, 59, 72, R.drawable.monster_v091_021),
            new Enemy("V091-022", "Pažeistas laužo feniksas", "PELENŲ NEKROPOLIS", "Atgimstantis plėšrūnas", "nekrotinis atsparumas", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – nekrotinis atsparumas; kovoje jis veikia kaip atgimstantis plėšrūnas.", 8, 407, 71, 62, 79, R.drawable.monster_v091_022),
            new Enemy("V091-023", "Sulydytas skeletų legionierius", "PELENŲ NEKROPOLIS", "Būrio vadas", "žarijų šuolis", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – žarijų šuolis; kovoje jis veikia kaip būrio vadas.", 9, 460, 81, 71, 74, R.drawable.monster_v091_023),
            new Enemy("V091-024", "Senovinis kapo globėjas", "PELENŲ NEKROPOLIS", "Senovinis globėjas", "kapų grandinės", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – kapų grandinės; kovoje jis veikia kaip senovinis globėjas.", 9, 471, 84, 74, 81, R.drawable.monster_v091_024),
            new Enemy("V091-025", "Vulkaninis mirties drakonas", "PELENŲ NEKROPOLIS", "Pasaulio grėsmė", "juodoji liepsna", "Pelenų nekropolio kapuose sutinkamas priešas. Pavojingiausias jo bruožas – juodoji liepsna; kovoje jis veikia kaip pasaulio grėsmė.", 10, 524, 82, 68, 93, R.drawable.monster_v091_025),
            new Enemy("V091-026", "Erškėčių vilkas", "KRAUJŠAKNĖS GIRIA", "Medžiotojas", "nuodų dygliai", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – nuodų dygliai; kovoje jis veikia kaip medžiotojas.", 2, 149, 26, 23, 41, R.drawable.monster_v091_026),
            new Enemy("V091-027", "Samaninis šernas", "KRAUJŠAKNĖS GIRIA", "Persekiotojas", "šaknų spąstai", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – šaknų spąstai; kovoje jis veikia kaip persekiotojas.", 3, 202, 36, 32, 53, R.drawable.monster_v091_027),
            new Enemy("V091-028", "Grybų ragų elnias", "KRAUJŠAKNĖS GIRIA", "Sargas", "sporų debesis", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – sporų debesis; kovoje jis veikia kaip sargas.", 3, 213, 39, 35, 43, R.drawable.monster_v091_028),
            new Enemy("V091-029", "Vijoklių ragana", "KRAUJŠAKNĖS GIRIA", "Pasalūnas", "samanų šarvas", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – samanų šarvas; kovoje jis veikia kaip pasalūnas.", 4, 266, 49, 44, 55, R.drawable.monster_v091_029),
            new Enemy("V091-030", "Pelkės tykūnas", "KRAUJŠAKNĖS GIRIA", "Ritualistas", "gyvybės siurbimas", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – gyvybės siurbimas; kovoje jis veikia kaip ritualistas.", 4, 277, 40, 32, 62, R.drawable.monster_v091_030),
            new Enemy("V091-031", "Pelkynų hidra", "KRAUJŠAKNĖS GIRIA", "Žvalgas", "nuodų dygliai", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – nuodų dygliai; kovoje jis veikia kaip žvalgas.", 4, 233, 43, 35, 52, R.drawable.monster_v091_031),
            new Enemy("V091-032", "Plėšrioji orchidėja", "KRAUJŠAKNĖS GIRIA", "Naikintojas", "šaknų spąstai", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – šaknų spąstai; kovoje jis veikia kaip naikintojas.", 5, 286, 53, 44, 64, R.drawable.monster_v091_032),
            new Enemy("V091-033", "Žievės trolis", "KRAUJŠAKNĖS GIRIA", "Dvikovininkas", "sporų debesis", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – sporų debesis; kovoje jis veikia kaip dvikovininkas.", 5, 297, 56, 47, 54, R.drawable.monster_v091_033),
            new Enemy("V091-034", "Maro rupūžė", "KRAUJŠAKNĖS GIRIA", "Spąstų kūrėjas", "samanų šarvas", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – samanų šarvas; kovoje jis veikia kaip spąstų kūrėjas.", 5, 308, 47, 50, 61, R.drawable.monster_v091_034),
            new Enemy("V091-035", "Šaknų voras", "KRAUJŠAKNĖS GIRIA", "Smogikas", "gyvybės siurbimas", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – gyvybės siurbimas; kovoje jis veikia kaip smogikas.", 6, 361, 57, 44, 73, R.drawable.monster_v091_035),
            new Enemy("V091-036", "Gluosnio raudotoja", "KRAUJŠAKNĖS GIRIA", "Teritorijos sargas", "nuodų dygliai", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – nuodų dygliai; kovoje jis veikia kaip teritorijos sargas.", 5, 275, 53, 41, 58, R.drawable.monster_v091_036),
            new Enemy("V091-037", "Grybienos riteris", "KRAUJŠAKNĖS GIRIA", "Skrendantis medžiotojas", "šaknų spąstai", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – šaknų spąstai; kovoje jis veikia kaip skrendantis medžiotojas.", 6, 328, 63, 50, 70, R.drawable.monster_v091_037),
            new Enemy("V091-038", "Pelkių krokodilas drake'as", "KRAUJŠAKNĖS GIRIA", "Silpnintojas", "sporų debesis", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – sporų debesis; kovoje jis veikia kaip silpnintojas.", 6, 339, 54, 53, 60, R.drawable.monster_v091_038),
            new Enemy("V091-039", "Žibintinė kandis", "KRAUJŠAKNĖS GIRIA", "Pramušėjas", "samanų šarvas", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – samanų šarvas; kovoje jis veikia kaip pramušėjas.", 6, 350, 57, 56, 67, R.drawable.monster_v091_039),
            new Enemy("V091-040", "Šarvuotoji dėlių karalienė", "KRAUJŠAKNĖS GIRIA", "Kontrolierius", "gyvybės siurbimas", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – gyvybės siurbimas; kovoje jis veikia kaip kontrolierius.", 7, 403, 67, 50, 79, R.drawable.monster_v091_040),
            new Enemy("V091-041", "Raguotasis girios globėjas", "KRAUJŠAKNĖS GIRIA", "Burtininkas", "nuodų dygliai", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – nuodų dygliai; kovoje jis veikia kaip burtininkas.", 6, 317, 63, 47, 64, R.drawable.monster_v091_041),
            new Enemy("V091-042", "Liūno ragana", "KRAUJŠAKNĖS GIRIA", "Greitas puolėjas", "šaknų spąstai", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – šaknų spąstai; kovoje jis veikia kaip greitas puolėjas.", 7, 370, 61, 56, 76, R.drawable.monster_v091_042),
            new Enemy("V091-043", "Plėšrusis medis", "KRAUJŠAKNĖS GIRIA", "Aukštumų sargas", "sporų debesis", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – sporų debesis; kovoje jis veikia kaip aukštumų sargas.", 7, 381, 64, 59, 66, R.drawable.monster_v091_043),
            new Enemy("V091-044", "Pelkės baziliskas", "KRAUJŠAKNĖS GIRIA", "Minios laužytojas", "samanų šarvas", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – samanų šarvas; kovoje jis veikia kaip minios laužytojas.", 7, 392, 67, 62, 73, R.drawable.monster_v091_044),
            new Enemy("V091-045", "Grybų kolosas", "KRAUJŠAKNĖS GIRIA", "Nuodytojas", "gyvybės siurbimas", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – gyvybės siurbimas; kovoje jis veikia kaip nuodytojas.", 8, 445, 77, 56, 68, R.drawable.monster_v091_045),
            new Enemy("V091-046", "Jaunoji Kraujšaknė", "KRAUJŠAKNĖS GIRIA", "Elitinis sargas", "nuodų dygliai", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – nuodų dygliai; kovoje jis veikia kaip elitinis sargas.", 8, 401, 68, 59, 75, R.drawable.monster_v091_046),
            new Enemy("V091-047", "Nuskendęs entas", "KRAUJŠAKNĖS GIRIA", "Atgimstantis plėšrūnas", "šaknų spąstai", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – šaknų spąstai; kovoje jis veikia kaip atgimstantis plėšrūnas.", 8, 412, 71, 62, 82, R.drawable.monster_v091_047),
            new Enemy("V091-048", "Nuodingųjų žiedų titanas", "KRAUJŠAKNĖS GIRIA", "Būrio vadas", "sporų debesis", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – sporų debesis; kovoje jis veikia kaip būrio vadas.", 9, 465, 81, 71, 77, R.drawable.monster_v091_048),
            new Enemy("V091-049", "Senasis girios drakonas", "KRAUJŠAKNĖS GIRIA", "Senovinis globėjas", "samanų šarvas", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – samanų šarvas; kovoje jis veikia kaip senovinis globėjas.", 9, 476, 84, 74, 84, R.drawable.monster_v091_049),
            new Enemy("V091-050", "Gyvoji pelkės tvirtovė", "KRAUJŠAKNĖS GIRIA", "Pasaulio grėsmė", "gyvybės siurbimas", "Kraujšaknės girios pelkynuose sutinkamas priešas. Pavojingiausias jo bruožas – gyvybės siurbimas; kovoje jis veikia kaip pasaulio grėsmė.", 10, 529, 82, 68, 79, R.drawable.monster_v091_050),
            new Enemy("V091-051", "Uolinis avinas", "GELEŽINĖS VIRŠŪNĖS", "Medžiotojas", "uolų šarvas", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – uolų šarvas; kovoje jis veikia kaip medžiotojas.", 2, 154, 26, 23, 44, R.drawable.monster_v091_051),
            new Enemy("V091-052", "Blyškusis urvų siaubūnas", "GELEŽINĖS VIRŠŪNĖS", "Persekiotojas", "lavinos smūgis", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – lavinos smūgis; kovoje jis veikia kaip persekiotojas.", 3, 207, 36, 32, 56, R.drawable.monster_v091_052),
            new Enemy("V091-053", "Geležinis kalnų erelis", "GELEŽINĖS VIRŠŪNĖS", "Sargas", "kristalų atspindys", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – kristalų atspindys; kovoje jis veikia kaip sargas.", 3, 218, 39, 35, 46, R.drawable.monster_v091_053),
            new Enemy("V091-054", "Kristalinė angis", "GELEŽINĖS VIRŠŪNĖS", "Pasalūnas", "kalvės kaitra", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – kalvės kaitra; kovoje jis veikia kaip pasalūnas.", 4, 271, 49, 44, 58, R.drawable.monster_v091_054),
            new Enemy("V091-055", "Uolų trolis", "GELEŽINĖS VIRŠŪNĖS", "Ritualistas", "audros krūvis", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – audros krūvis; kovoje jis veikia kaip ritualistas.", 4, 282, 40, 32, 48, R.drawable.monster_v091_055),
            new Enemy("V091-056", "Rūdos vabalas", "GELEŽINĖS VIRŠŪNĖS", "Žvalgas", "uolų šarvas", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – uolų šarvas; kovoje jis veikia kaip žvalgas.", 4, 238, 43, 35, 55, R.drawable.monster_v091_056),
            new Enemy("V091-057", "Lavinos milžinas", "GELEŽINĖS VIRŠŪNĖS", "Naikintojas", "lavinos smūgis", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – lavinos smūgis; kovoje jis veikia kaip naikintojas.", 5, 291, 53, 44, 67, R.drawable.monster_v091_057),
            new Enemy("V091-058", "Magmos salamandra", "GELEŽINĖS VIRŠŪNĖS", "Dvikovininkas", "kristalų atspindys", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – kristalų atspindys; kovoje jis veikia kaip dvikovininkas.", 5, 302, 56, 47, 57, R.drawable.monster_v091_058),
            new Enemy("V091-059", "Audros vyvernas", "GELEŽINĖS VIRŠŪNĖS", "Spąstų kūrėjas", "kalvės kaitra", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – kalvės kaitra; kovoje jis veikia kaip spąstų kūrėjas.", 5, 313, 47, 50, 64, R.drawable.monster_v091_059),
            new Enemy("V091-060", "Akmeninis baziliskas", "GELEŽINĖS VIRŠŪNĖS", "Smogikas", "audros krūvis", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – audros krūvis; kovoje jis veikia kaip smogikas.", 6, 366, 57, 44, 59, R.drawable.monster_v091_060),
            new Enemy("V091-061", "Runų minotauras", "GELEŽINĖS VIRŠŪNĖS", "Teritorijos sargas", "uolų šarvas", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – uolų šarvas; kovoje jis veikia kaip teritorijos sargas.", 5, 280, 53, 41, 61, R.drawable.monster_v091_061),
            new Enemy("V091-062", "Kristalų harpija", "GELEŽINĖS VIRŠŪNĖS", "Skrendantis medžiotojas", "lavinos smūgis", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – lavinos smūgis; kovoje jis veikia kaip skrendantis medžiotojas.", 6, 333, 63, 50, 73, R.drawable.monster_v091_062),
            new Enemy("V091-063", "Grandinėtas ciklopas", "GELEŽINĖS VIRŠŪNĖS", "Silpnintojas", "kristalų atspindys", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – kristalų atspindys; kovoje jis veikia kaip silpnintojas.", 6, 344, 54, 53, 63, R.drawable.monster_v091_063),
            new Enemy("V091-064", "Obsidiano gręžikas", "GELEŽINĖS VIRŠŪNĖS", "Pramušėjas", "kalvės kaitra", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – kalvės kaitra; kovoje jis veikia kaip pramušėjas.", 6, 355, 57, 56, 70, R.drawable.monster_v091_064),
            new Enemy("V091-065", "Kalnų lichas", "GELEŽINĖS VIRŠŪNĖS", "Kontrolierius", "audros krūvis", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – audros krūvis; kovoje jis veikia kaip kontrolierius.", 7, 408, 67, 50, 65, R.drawable.monster_v091_065),
            new Enemy("V091-066", "Perkūno paukštis", "GELEŽINĖS VIRŠŪNĖS", "Burtininkas", "uolų šarvas", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – uolų šarvas; kovoje jis veikia kaip burtininkas.", 6, 322, 63, 47, 67, R.drawable.monster_v091_066),
            new Enemy("V091-067", "Kalvės demonas", "GELEŽINĖS VIRŠŪNĖS", "Greitas puolėjas", "lavinos smūgis", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – lavinos smūgis; kovoje jis veikia kaip greitas puolėjas.", 7, 375, 61, 56, 79, R.drawable.monster_v091_067),
            new Enemy("V091-068", "Kvarco golemas", "GELEŽINĖS VIRŠŪNĖS", "Aukštumų sargas", "kristalų atspindys", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – kristalų atspindys; kovoje jis veikia kaip aukštumų sargas.", 7, 386, 64, 59, 69, R.drawable.monster_v091_068),
            new Enemy("V091-069", "Granito hidra", "GELEŽINĖS VIRŠŪNĖS", "Minios laužytojas", "kalvės kaitra", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – kalvės kaitra; kovoje jis veikia kaip minios laužytojas.", 7, 397, 67, 62, 76, R.drawable.monster_v091_069),
            new Enemy("V091-070", "Viršūnių revenantas", "GELEŽINĖS VIRŠŪNĖS", "Nuodytojas", "audros krūvis", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – audros krūvis; kovoje jis veikia kaip nuodytojas.", 8, 450, 77, 56, 71, R.drawable.monster_v091_070),
            new Enemy("V091-071", "Gelmių titanas", "GELEŽINĖS VIRŠŪNĖS", "Elitinis sargas", "uolų šarvas", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – uolų šarvas; kovoje jis veikia kaip elitinis sargas.", 8, 406, 68, 59, 78, R.drawable.monster_v091_071),
            new Enemy("V091-072", "Dangaus laužytojas", "GELEŽINĖS VIRŠŪNĖS", "Atgimstantis plėšrūnas", "lavinos smūgis", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – lavinos smūgis; kovoje jis veikia kaip atgimstantis plėšrūnas.", 8, 417, 71, 62, 68, R.drawable.monster_v091_072),
            new Enemy("V091-073", "Gyvosios citadelės golemas", "GELEŽINĖS VIRŠŪNĖS", "Būrio vadas", "kristalų atspindys", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – kristalų atspindys; kovoje jis veikia kaip būrio vadas.", 9, 470, 81, 71, 80, R.drawable.monster_v091_073),
            new Enemy("V091-074", "Vulkaninis wyrmas", "GELEŽINĖS VIRŠŪNĖS", "Senovinis globėjas", "kalvės kaitra", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – kalvės kaitra; kovoje jis veikia kaip senovinis globėjas.", 9, 481, 84, 74, 87, R.drawable.monster_v091_074),
            new Enemy("V091-075", "Senovinis kalnų karalius", "GELEŽINĖS VIRŠŪNĖS", "Pasaulio grėsmė", "audros krūvis", "Geležinių Viršūnių perėjose sutinkamas priešas. Pavojingiausias jo bruožas – audros krūvis; kovoje jis veikia kaip pasaulio grėsmė.", 10, 534, 82, 68, 82, R.drawable.monster_v091_075),
            new Enemy("V091-076", "Plyšio skalikas", "MERIDIANO TUŠTUMA", "Medžiotojas", "fazės poslinkis", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – fazės poslinkis; kovoje jis veikia kaip medžiotojas.", 2, 159, 26, 23, 47, R.drawable.monster_v091_076),
            new Enemy("V091-077", "Veidrodžio šmėkla", "MERIDIANO TUŠTUMA", "Persekiotojas", "gravitacijos lūžis", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – gravitacijos lūžis; kovoje jis veikia kaip persekiotojas.", 3, 212, 36, 32, 59, R.drawable.monster_v091_077),
            new Enemy("V091-078", "Fazinis voras", "MERIDIANO TUŠTUMA", "Sargas", "atminties vagystė", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – atminties vagystė; kovoje jis veikia kaip sargas.", 3, 223, 39, 35, 49, R.drawable.monster_v091_078),
            new Enemy("V091-079", "Nulinio stiklo riteris", "MERIDIANO TUŠTUMA", "Pasalūnas", "nulinio stiklo oda", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – nulinio stiklo oda; kovoje jis veikia kaip pasalūnas.", 4, 276, 49, 44, 61, R.drawable.monster_v091_079),
            new Enemy("V091-080", "Rezonanso ungurys", "MERIDIANO TUŠTUMA", "Ritualistas", "paradokso laukas", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – paradokso laukas; kovoje jis veikia kaip ritualistas.", 4, 287, 40, 32, 51, R.drawable.monster_v091_080),
            new Enemy("V091-081", "Daugiakė anomalija", "MERIDIANO TUŠTUMA", "Žvalgas", "fazės poslinkis", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – fazės poslinkis; kovoje jis veikia kaip žvalgas.", 4, 243, 43, 35, 58, R.drawable.monster_v091_081),
            new Enemy("V091-082", "Laiko revenantas", "MERIDIANO TUŠTUMA", "Naikintojas", "gravitacijos lūžis", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – gravitacijos lūžis; kovoje jis veikia kaip naikintojas.", 5, 296, 53, 44, 53, R.drawable.monster_v091_082),
            new Enemy("V091-083", "Gyvasis aido mimikas", "MERIDIANO TUŠTUMA", "Dvikovininkas", "atminties vagystė", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – atminties vagystė; kovoje jis veikia kaip dvikovininkas.", 5, 307, 56, 47, 60, R.drawable.monster_v091_083),
            new Enemy("V091-084", "Gravitacijos žvėris", "MERIDIANO TUŠTUMA", "Spąstų kūrėjas", "nulinio stiklo oda", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – nulinio stiklo oda; kovoje jis veikia kaip spąstų kūrėjas.", 5, 318, 47, 50, 67, R.drawable.monster_v091_084),
            new Enemy("V091-085", "Astralinis parazitas", "MERIDIANO TUŠTUMA", "Smogikas", "paradokso laukas", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – paradokso laukas; kovoje jis veikia kaip smogikas.", 6, 371, 57, 44, 62, R.drawable.monster_v091_085),
            new Enemy("V091-086", "Sklandantis šukių golemas", "MERIDIANO TUŠTUMA", "Teritorijos sargas", "fazės poslinkis", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – fazės poslinkis; kovoje jis veikia kaip teritorijos sargas.", 5, 285, 53, 41, 64, R.drawable.monster_v091_086),
            new Enemy("V091-087", "Beveidis tuštumos vienuolis", "MERIDIANO TUŠTUMA", "Skrendantis medžiotojas", "gravitacijos lūžis", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – gravitacijos lūžis; kovoje jis veikia kaip skrendantis medžiotojas.", 6, 338, 63, 50, 59, R.drawable.monster_v091_087),
            new Enemy("V091-088", "Anomalijos kandis", "MERIDIANO TUŠTUMA", "Silpnintojas", "atminties vagystė", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – atminties vagystė; kovoje jis veikia kaip silpnintojas.", 6, 349, 54, 53, 66, R.drawable.monster_v091_088),
            new Enemy("V091-089", "Portalo gyvatė", "MERIDIANO TUŠTUMA", "Pramušėjas", "nulinio stiklo oda", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – nulinio stiklo oda; kovoje jis veikia kaip pramušėjas.", 6, 360, 57, 56, 73, R.drawable.monster_v091_089),
            new Enemy("V091-090", "Skelto kūno persekiotojas", "MERIDIANO TUŠTUMA", "Kontrolierius", "paradokso laukas", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – paradokso laukas; kovoje jis veikia kaip kontrolierius.", 7, 413, 67, 50, 68, R.drawable.monster_v091_090),
            new Enemy("V091-091", "Bežvaigždis angelas", "MERIDIANO TUŠTUMA", "Burtininkas", "fazės poslinkis", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – fazės poslinkis; kovoje jis veikia kaip burtininkas.", 6, 327, 63, 47, 70, R.drawable.monster_v091_091),
            new Enemy("V091-092", "Paradokso hidra", "MERIDIANO TUŠTUMA", "Greitas puolėjas", "gravitacijos lūžis", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – gravitacijos lūžis; kovoje jis veikia kaip greitas puolėjas.", 7, 380, 61, 56, 65, R.drawable.monster_v091_092),
            new Enemy("V091-093", "Atminties ėdikas", "MERIDIANO TUŠTUMA", "Aukštumų sargas", "atminties vagystė", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – atminties vagystė; kovoje jis veikia kaip aukštumų sargas.", 7, 391, 64, 59, 72, R.drawable.monster_v091_093),
            new Enemy("V091-094", "Juodosios saulės kunigas", "MERIDIANO TUŠTUMA", "Minios laužytojas", "nulinio stiklo oda", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – nulinio stiklo oda; kovoje jis veikia kaip minios laužytojas.", 7, 402, 67, 62, 79, R.drawable.monster_v091_094),
            new Enemy("V091-095", "Gardelės žvėris", "MERIDIANO TUŠTUMA", "Nuodytojas", "paradokso laukas", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – paradokso laukas; kovoje jis veikia kaip nuodytojas.", 8, 455, 77, 56, 74, R.drawable.monster_v091_095),
            new Enemy("V091-096", "Meridiano orakulas", "MERIDIANO TUŠTUMA", "Elitinis sargas", "fazės poslinkis", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – fazės poslinkis; kovoje jis veikia kaip elitinis sargas.", 8, 411, 68, 59, 81, R.drawable.monster_v091_096),
            new Enemy("V091-097", "Horizonto titanas", "MERIDIANO TUŠTUMA", "Atgimstantis plėšrūnas", "gravitacijos lūžis", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – gravitacijos lūžis; kovoje jis veikia kaip atgimstantis plėšrūnas.", 8, 422, 71, 62, 71, R.drawable.monster_v091_097),
            new Enemy("V091-098", "Tuštumos banginis", "MERIDIANO TUŠTUMA", "Būrio vadas", "atminties vagystė", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – atminties vagystė; kovoje jis veikia kaip būrio vadas.", 9, 475, 81, 71, 83, R.drawable.monster_v091_098),
            new Enemy("V091-099", "Suskilusio dievo avataras", "MERIDIANO TUŠTUMA", "Senovinis globėjas", "nulinio stiklo oda", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – nulinio stiklo oda; kovoje jis veikia kaip senovinis globėjas.", 9, 486, 84, 74, 73, R.drawable.monster_v091_099),
            new Enemy("V091-100", "Plyšio drakonas", "MERIDIANO TUŠTUMA", "Pasaulio grėsmė", "paradokso laukas", "Meridiano Tuštumos plyšiuose sutinkamas priešas. Pavojingiausias jo bruožas – paradokso laukas; kovoje jis veikia kaip pasaulio grėsmė.", 10, 539, 82, 68, 85, R.drawable.monster_v091_100),
            new Enemy("V091-101", "Mechaninis kranklys", "UŽMIRŠTOS DIRBTUVĖS", "Medžiotojas", "krumpliaračių spąstai", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – krumpliaračių spąstai; kovoje jis veikia kaip medžiotojas.", 2, 164, 26, 23, 50, R.drawable.monster_v091_101),
            new Enemy("V091-102", "Bronzinis vilkas", "UŽMIRŠTOS DIRBTUVĖS", "Persekiotojas", "runinis skydas", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – runinis skydas; kovoje jis veikia kaip persekiotojas.", 3, 217, 36, 32, 45, R.drawable.monster_v091_102),
            new Enemy("V091-103", "Runinis sargybinis", "UŽMIRŠTOS DIRBTUVĖS", "Sargas", "magnetinė trauka", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – magnetinė trauka; kovoje jis veikia kaip sargas.", 3, 228, 39, 35, 52, R.drawable.monster_v091_103),
            new Enemy("V091-104", "Grandininis automatas", "UŽMIRŠTOS DIRBTUVĖS", "Pasalūnas", "krosnies kaitra", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – krosnies kaitra; kovoje jis veikia kaip pasalūnas.", 4, 281, 49, 44, 64, R.drawable.monster_v091_104),
            new Enemy("V091-105", "Žibintgalvis golemas", "UŽMIRŠTOS DIRBTUVĖS", "Ritualistas", "mechaninis persitvarkymas", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – mechaninis persitvarkymas; kovoje jis veikia kaip ritualistas.", 4, 292, 40, 32, 54, R.drawable.monster_v091_105),
            new Enemy("V091-106", "Ašmenų skarabėjų motinėlė", "UŽMIRŠTOS DIRBTUVĖS", "Žvalgas", "krumpliaračių spąstai", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – krumpliaračių spąstai; kovoje jis veikia kaip žvalgas.", 4, 248, 43, 35, 61, R.drawable.monster_v091_106),
            new Enemy("V091-107", "Žalvarinis kentauras", "UŽMIRŠTOS DIRBTUVĖS", "Naikintojas", "runinis skydas", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – runinis skydas; kovoje jis veikia kaip naikintojas.", 5, 301, 53, 44, 56, R.drawable.monster_v091_107),
            new Enemy("V091-108", "Apgulties mimikas", "UŽMIRŠTOS DIRBTUVĖS", "Dvikovininkas", "magnetinė trauka", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – magnetinė trauka; kovoje jis veikia kaip dvikovininkas.", 5, 312, 56, 47, 63, R.drawable.monster_v091_108),
            new Enemy("V091-109", "Arkaninis bokštelis", "UŽMIRŠTOS DIRBTUVĖS", "Spąstų kūrėjas", "krosnies kaitra", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – krosnies kaitra; kovoje jis veikia kaip spąstų kūrėjas.", 5, 323, 47, 50, 53, R.drawable.monster_v091_109),
            new Enemy("V091-110", "Geležinis vienuolis", "UŽMIRŠTOS DIRBTUVĖS", "Smogikas", "mechaninis persitvarkymas", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – mechaninis persitvarkymas; kovoje jis veikia kaip smogikas.", 6, 376, 57, 44, 65, R.drawable.monster_v091_110),
            new Enemy("V091-111", "Prakeikta porceliano lėlė", "UŽMIRŠTOS DIRBTUVĖS", "Teritorijos sargas", "krumpliaračių spąstai", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – krumpliaračių spąstai; kovoje jis veikia kaip teritorijos sargas.", 5, 290, 53, 41, 67, R.drawable.monster_v091_111),
            new Enemy("V091-112", "Laikrodinis voras", "UŽMIRŠTOS DIRBTUVĖS", "Skrendantis medžiotojas", "runinis skydas", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – runinis skydas; kovoje jis veikia kaip skrendantis medžiotojas.", 6, 343, 63, 50, 62, R.drawable.monster_v091_112),
            new Enemy("V091-113", "Tušti gyvieji šarvai", "UŽMIRŠTOS DIRBTUVĖS", "Silpnintojas", "magnetinė trauka", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – magnetinė trauka; kovoje jis veikia kaip silpnintojas.", 6, 354, 54, 53, 69, R.drawable.monster_v091_113),
            new Enemy("V091-114", "Krumpliaračių gyvatė", "UŽMIRŠTOS DIRBTUVĖS", "Pramušėjas", "krosnies kaitra", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – krosnies kaitra; kovoje jis veikia kaip pramušėjas.", 6, 365, 57, 56, 59, R.drawable.monster_v091_114),
            new Enemy("V091-115", "Krosnies riteris", "UŽMIRŠTOS DIRBTUVĖS", "Kontrolierius", "mechaninis persitvarkymas", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – mechaninis persitvarkymas; kovoje jis veikia kaip kontrolierius.", 7, 418, 67, 50, 71, R.drawable.monster_v091_115),
            new Enemy("V091-116", "Titano plaštaka", "UŽMIRŠTOS DIRBTUVĖS", "Burtininkas", "krumpliaračių spąstai", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – krumpliaračių spąstai; kovoje jis veikia kaip burtininkas.", 6, 332, 63, 47, 73, R.drawable.monster_v091_116),
            new Enemy("V091-117", "Katedros automatas", "UŽMIRŠTOS DIRBTUVĖS", "Greitas puolėjas", "runinis skydas", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – runinis skydas; kovoje jis veikia kaip greitas puolėjas.", 7, 385, 61, 56, 68, R.drawable.monster_v091_117),
            new Enemy("V091-118", "Alcheminis homunkulas", "UŽMIRŠTOS DIRBTUVĖS", "Aukštumų sargas", "magnetinė trauka", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – magnetinė trauka; kovoje jis veikia kaip aukštumų sargas.", 7, 396, 64, 59, 75, R.drawable.monster_v091_118),
            new Enemy("V091-119", "Magnetinis šukių golemas", "UŽMIRŠTOS DIRBTUVĖS", "Minios laužytojas", "krosnies kaitra", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – krosnies kaitra; kovoje jis veikia kaip minios laužytojas.", 7, 407, 67, 62, 65, R.drawable.monster_v091_119),
            new Enemy("V091-120", "Sudužusi orakulo mašina", "UŽMIRŠTOS DIRBTUVĖS", "Nuodytojas", "mechaninis persitvarkymas", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – mechaninis persitvarkymas; kovoje jis veikia kaip nuodytojas.", 8, 460, 77, 56, 77, R.drawable.monster_v091_120),
            new Enemy("V091-121", "Senovinė karo mašina", "UŽMIRŠTOS DIRBTUVĖS", "Elitinis sargas", "krumpliaračių spąstai", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – krumpliaračių spąstai; kovoje jis veikia kaip elitinis sargas.", 8, 416, 68, 59, 84, R.drawable.monster_v091_121),
            new Enemy("V091-122", "Mechaninis kolosas", "UŽMIRŠTOS DIRBTUVĖS", "Atgimstantis plėšrūnas", "runinis skydas", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – runinis skydas; kovoje jis veikia kaip atgimstantis plėšrūnas.", 8, 427, 71, 62, 74, R.drawable.monster_v091_122),
            new Enemy("V091-123", "Vaikščiojanti tvirtovė", "UŽMIRŠTOS DIRBTUVĖS", "Būrio vadas", "magnetinė trauka", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – magnetinė trauka; kovoje jis veikia kaip būrio vadas.", 9, 480, 81, 71, 86, R.drawable.monster_v091_123),
            new Enemy("V091-124", "Saulės kalvės serafas", "UŽMIRŠTOS DIRBTUVĖS", "Senovinis globėjas", "krosnies kaitra", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – krosnies kaitra; kovoje jis veikia kaip senovinis globėjas.", 9, 491, 84, 74, 76, R.drawable.monster_v091_124),
            new Enemy("V091-125", "Griuvėsių metalinis drakonas", "UŽMIRŠTOS DIRBTUVĖS", "Pasaulio grėsmė", "mechaninis persitvarkymas", "Užmirštų dirbtuvių griuvėsiuose sutinkamas priešas. Pavojingiausias jo bruožas – mechaninis persitvarkymas; kovoje jis veikia kaip pasaulio grėsmė.", 10, 544, 82, 68, 88, R.drawable.monster_v091_125),
            new Enemy("V091-126", "Druskos lavonas", "BEDUGNĖS PAKRANTĖ", "Medžiotojas", "skendimo prakeiksmas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – skendimo prakeiksmas; kovoje jis veikia kaip medžiotojas.", 2, 169, 26, 23, 53, R.drawable.monster_v091_126),
            new Enemy("V091-127", "Rifo skalikas", "BEDUGNĖS PAKRANTĖ", "Persekiotojas", "koralų šarvas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – koralų šarvas; kovoje jis veikia kaip persekiotojas.", 3, 222, 36, 32, 48, R.drawable.monster_v091_127),
            new Enemy("V091-128", "Nuskendusio jūreivio šmėkla", "BEDUGNĖS PAKRANTĖ", "Sargas", "bioliuminescencinė apgaulė", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – bioliuminescencinė apgaulė; kovoje jis veikia kaip sargas.", 3, 233, 39, 35, 55, R.drawable.monster_v091_128),
            new Enemy("V091-129", "Kiauto krabų smogikas", "BEDUGNĖS PAKRANTĖ", "Pasalūnas", "potvynio smūgis", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – potvynio smūgis; kovoje jis veikia kaip pasalūnas.", 4, 286, 49, 44, 50, R.drawable.monster_v091_129),
            new Enemy("V091-130", "Plėšrioji sirena", "BEDUGNĖS PAKRANTĖ", "Ritualistas", "gelmių spaudimas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – gelmių spaudimas; kovoje jis veikia kaip ritualistas.", 4, 297, 40, 32, 57, R.drawable.monster_v091_130),
            new Enemy("V091-131", "Gelmių žibintžuvė", "BEDUGNĖS PAKRANTĖ", "Žvalgas", "skendimo prakeiksmas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – skendimo prakeiksmas; kovoje jis veikia kaip žvalgas.", 4, 253, 43, 35, 64, R.drawable.monster_v091_131),
            new Enemy("V091-132", "Kriauklėtas riteris", "BEDUGNĖS PAKRANTĖ", "Naikintojas", "koralų šarvas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – koralų šarvas; kovoje jis veikia kaip naikintojas.", 5, 306, 53, 44, 59, R.drawable.monster_v091_132),
            new Enemy("V091-133", "Medūzos orakulas", "BEDUGNĖS PAKRANTĖ", "Dvikovininkas", "bioliuminescencinė apgaulė", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – bioliuminescencinė apgaulė; kovoje jis veikia kaip dvikovininkas.", 5, 317, 56, 47, 66, R.drawable.monster_v091_133),
            new Enemy("V091-134", "Šarvuotas ungurys", "BEDUGNĖS PAKRANTĖ", "Spąstų kūrėjas", "potvynio smūgis", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – potvynio smūgis; kovoje jis veikia kaip spąstų kūrėjas.", 5, 328, 47, 50, 56, R.drawable.monster_v091_134),
            new Enemy("V091-135", "Koralų golemas", "BEDUGNĖS PAKRANTĖ", "Smogikas", "gelmių spaudimas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – gelmių spaudimas; kovoje jis veikia kaip smogikas.", 6, 381, 57, 44, 68, R.drawable.monster_v091_135),
            new Enemy("V091-136", "Krakeno palikuonis", "BEDUGNĖS PAKRANTĖ", "Teritorijos sargas", "skendimo prakeiksmas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – skendimo prakeiksmas; kovoje jis veikia kaip teritorijos sargas.", 5, 295, 53, 41, 53, R.drawable.monster_v091_136),
            new Enemy("V091-137", "Potvynių ragana", "BEDUGNĖS PAKRANTĖ", "Skrendantis medžiotojas", "koralų šarvas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – koralų šarvas; kovoje jis veikia kaip skrendantis medžiotojas.", 6, 348, 63, 50, 65, R.drawable.monster_v091_137),
            new Enemy("V091-138", "Ryklys revenantas", "BEDUGNĖS PAKRANTĖ", "Silpnintojas", "bioliuminescencinė apgaulė", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – bioliuminescencinė apgaulė; kovoje jis veikia kaip silpnintojas.", 6, 359, 54, 53, 72, R.drawable.monster_v091_138),
            new Enemy("V091-139", "Laivo nuolaužų mimikas", "BEDUGNĖS PAKRANTĖ", "Pramušėjas", "potvynio smūgis", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – potvynio smūgis; kovoje jis veikia kaip pramušėjas.", 6, 370, 57, 56, 62, R.drawable.monster_v091_139),
            new Enemy("V091-140", "Bedugnės medūza", "BEDUGNĖS PAKRANTĖ", "Kontrolierius", "gelmių spaudimas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – gelmių spaudimas; kovoje jis veikia kaip kontrolierius.", 7, 423, 67, 50, 74, R.drawable.monster_v091_140),
            new Enemy("V091-141", "Leviatano kunigas", "BEDUGNĖS PAKRANTĖ", "Burtininkas", "skendimo prakeiksmas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – skendimo prakeiksmas; kovoje jis veikia kaip burtininkas.", 6, 337, 63, 47, 59, R.drawable.monster_v091_141),
            new Enemy("V091-142", "Nuskendęs karalius", "BEDUGNĖS PAKRANTĖ", "Greitas puolėjas", "koralų šarvas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – koralų šarvas; kovoje jis veikia kaip greitas puolėjas.", 7, 390, 61, 56, 71, R.drawable.monster_v091_142),
            new Enemy("V091-143", "Trišakio demonas", "BEDUGNĖS PAKRANTĖ", "Aukštumų sargas", "bioliuminescencinė apgaulė", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – bioliuminescencinė apgaulė; kovoje jis veikia kaip aukštumų sargas.", 7, 401, 64, 59, 78, R.drawable.monster_v091_143),
            new Enemy("V091-144", "Koralų hidra", "BEDUGNĖS PAKRANTĖ", "Minios laužytojas", "potvynio smūgis", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – potvynio smūgis; kovoje jis veikia kaip minios laužytojas.", 7, 412, 67, 62, 68, R.drawable.monster_v091_144),
            new Enemy("V091-145", "Juodvandenis begemotas", "BEDUGNĖS PAKRANTĖ", "Nuodytojas", "gelmių spaudimas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – gelmių spaudimas; kovoje jis veikia kaip nuodytojas.", 8, 465, 77, 56, 80, R.drawable.monster_v091_145),
            new Enemy("V091-146", "Bedugnės leviatanas", "BEDUGNĖS PAKRANTĖ", "Elitinis sargas", "skendimo prakeiksmas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – skendimo prakeiksmas; kovoje jis veikia kaip elitinis sargas.", 8, 421, 68, 59, 70, R.drawable.monster_v091_146),
            new Enemy("V091-147", "Vaikščiojantis švyturys", "BEDUGNĖS PAKRANTĖ", "Atgimstantis plėšrūnas", "koralų šarvas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – koralų šarvas; kovoje jis veikia kaip atgimstantis plėšrūnas.", 8, 432, 71, 62, 77, R.drawable.monster_v091_147),
            new Enemy("V091-148", "Tvirtovinis krabas", "BEDUGNĖS PAKRANTĖ", "Būrio vadas", "bioliuminescencinė apgaulė", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – bioliuminescencinė apgaulė; kovoje jis veikia kaip būrio vadas.", 9, 485, 81, 71, 89, R.drawable.monster_v091_148),
            new Enemy("V091-149", "Gelmių drakonas", "BEDUGNĖS PAKRANTĖ", "Senovinis globėjas", "potvynio smūgis", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – potvynio smūgis; kovoje jis veikia kaip senovinis globėjas.", 9, 496, 84, 74, 79, R.drawable.monster_v091_149),
            new Enemy("V091-150", "Raudonosios įdubos dievaitis", "BEDUGNĖS PAKRANTĖ", "Pasaulio grėsmė", "gelmių spaudimas", "Bedugnės Pakrantės vandenyse sutinkamas priešas. Pavojingiausias jo bruožas – gelmių spaudimas; kovoje jis veikia kaip pasaulio grėsmė.", 10, 549, 82, 68, 91, R.drawable.monster_v091_150),
            new Enemy("V091-151", "Ledšarvis vilkas", "AUDRŲ ŠIAURĖ", "Medžiotojas", "šerkšno šarvas", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – šerkšno šarvas; kovoje jis veikia kaip medžiotojas.", 2, 174, 26, 23, 39, R.drawable.monster_v091_151),
            new Enemy("V091-152", "Šalčio goblinas", "AUDRŲ ŠIAURĖ", "Persekiotojas", "pūgos šydas", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – pūgos šydas; kovoje jis veikia kaip persekiotojas.", 3, 227, 36, 32, 51, R.drawable.monster_v091_152),
            new Enemy("V091-153", "Sniego harpija", "AUDRŲ ŠIAURĖ", "Sargas", "žaibo krūvis", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – žaibo krūvis; kovoje jis veikia kaip sargas.", 3, 238, 39, 35, 58, R.drawable.monster_v091_153),
            new Enemy("V091-154", "Šerkšno riteris", "AUDRŲ ŠIAURĖ", "Pasalūnas", "ledo spąstai", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – ledo spąstai; kovoje jis veikia kaip pasalūnas.", 4, 291, 49, 44, 53, R.drawable.monster_v091_154),
            new Enemy("V091-155", "Kristalinė lapė", "AUDRŲ ŠIAURĖ", "Ritualistas", "pašvaistės blyksnis", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – pašvaistės blyksnis; kovoje jis veikia kaip ritualistas.", 4, 302, 40, 32, 60, R.drawable.monster_v091_155),
            new Enemy("V091-156", "Ledynų trolis", "AUDRŲ ŠIAURĖ", "Žvalgas", "šerkšno šarvas", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – šerkšno šarvas; kovoje jis veikia kaip žvalgas.", 4, 258, 43, 35, 50, R.drawable.monster_v091_156),
            new Enemy("V091-157", "Pūgos ragana", "AUDRŲ ŠIAURĖ", "Naikintojas", "pūgos šydas", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – pūgos šydas; kovoje jis veikia kaip naikintojas.", 5, 311, 53, 44, 62, R.drawable.monster_v091_157),
            new Enemy("V091-158", "Sušalęs didysis voras", "AUDRŲ ŠIAURĖ", "Dvikovininkas", "žaibo krūvis", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – žaibo krūvis; kovoje jis veikia kaip dvikovininkas.", 5, 322, 56, 47, 69, R.drawable.monster_v091_158),
            new Enemy("V091-159", "Žaibo ragų elnias", "AUDRŲ ŠIAURĖ", "Spąstų kūrėjas", "ledo spąstai", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – ledo spąstai; kovoje jis veikia kaip spąstų kūrėjas.", 5, 333, 47, 50, 59, R.drawable.monster_v091_159),
            new Enemy("V091-160", "Krušos elementas", "AUDRŲ ŠIAURĖ", "Smogikas", "pašvaistės blyksnis", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – pašvaistės blyksnis; kovoje jis veikia kaip smogikas.", 6, 386, 57, 44, 71, R.drawable.monster_v091_160),
            new Enemy("V091-161", "Šalčio milžinas", "AUDRŲ ŠIAURĖ", "Teritorijos sargas", "šerkšno šarvas", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – šerkšno šarvas; kovoje jis veikia kaip teritorijos sargas.", 5, 300, 53, 41, 56, R.drawable.monster_v091_161),
            new Enemy("V091-162", "Audros vienuolis", "AUDRŲ ŠIAURĖ", "Skrendantis medžiotojas", "pūgos šydas", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – pūgos šydas; kovoje jis veikia kaip skrendantis medžiotojas.", 6, 353, 63, 50, 68, R.drawable.monster_v091_162),
            new Enemy("V091-163", "Perkūno driežas", "AUDRŲ ŠIAURĖ", "Silpnintojas", "žaibo krūvis", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – žaibo krūvis; kovoje jis veikia kaip silpnintojas.", 6, 364, 54, 53, 58, R.drawable.monster_v091_163),
            new Enemy("V091-164", "Ledo gręžikas", "AUDRŲ ŠIAURĖ", "Pramušėjas", "ledo spąstai", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – ledo spąstai; kovoje jis veikia kaip pramušėjas.", 6, 375, 57, 56, 65, R.drawable.monster_v091_164),
            new Enemy("V091-165", "Pašvaistės šmėkla", "AUDRŲ ŠIAURĖ", "Kontrolierius", "pašvaistės blyksnis", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – pašvaistės blyksnis; kovoje jis veikia kaip kontrolierius.", 7, 428, 67, 50, 77, R.drawable.monster_v091_165),
            new Enemy("V091-166", "Ledyno golemas", "AUDRŲ ŠIAURĖ", "Burtininkas", "šerkšno šarvas", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – šerkšno šarvas; kovoje jis veikia kaip burtininkas.", 6, 342, 63, 47, 62, R.drawable.monster_v091_166),
            new Enemy("V091-167", "Audros erelis", "AUDRŲ ŠIAURĖ", "Greitas puolėjas", "pūgos šydas", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – pūgos šydas; kovoje jis veikia kaip greitas puolėjas.", 7, 395, 61, 56, 74, R.drawable.monster_v091_167),
            new Enemy("V091-168", "Sušalęs senovės karalius", "AUDRŲ ŠIAURĖ", "Aukštumų sargas", "žaibo krūvis", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – žaibo krūvis; kovoje jis veikia kaip aukštumų sargas.", 7, 406, 64, 59, 64, R.drawable.monster_v091_168),
            new Enemy("V091-169", "Debesų gyvatė", "AUDRŲ ŠIAURĖ", "Minios laužytojas", "ledo spąstai", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – ledo spąstai; kovoje jis veikia kaip minios laužytojas.", 7, 417, 67, 62, 71, R.drawable.monster_v091_169),
            new Enemy("V091-170", "Perkūno oni", "AUDRŲ ŠIAURĖ", "Nuodytojas", "pašvaistės blyksnis", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – pašvaistės blyksnis; kovoje jis veikia kaip nuodytojas.", 8, 470, 77, 56, 83, R.drawable.monster_v091_170),
            new Enemy("V091-171", "Žiemos titanas", "AUDRŲ ŠIAURĖ", "Elitinis sargas", "šerkšno šarvas", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – šerkšno šarvas; kovoje jis veikia kaip elitinis sargas.", 8, 426, 68, 59, 73, R.drawable.monster_v091_171),
            new Enemy("V091-172", "Audrų katedros žvėris", "AUDRŲ ŠIAURĖ", "Atgimstantis plėšrūnas", "pūgos šydas", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – pūgos šydas; kovoje jis veikia kaip atgimstantis plėšrūnas.", 8, 437, 71, 62, 80, R.drawable.monster_v091_172),
            new Enemy("V091-173", "Pašvaistės drakonas", "AUDRŲ ŠIAURĖ", "Būrio vadas", "žaibo krūvis", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – žaibo krūvis; kovoje jis veikia kaip būrio vadas.", 9, 490, 81, 71, 75, R.drawable.monster_v091_173),
            new Enemy("V091-174", "Baltosios pūgos leviatanas", "AUDRŲ ŠIAURĖ", "Senovinis globėjas", "ledo spąstai", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – ledo spąstai; kovoje jis veikia kaip senovinis globėjas.", 9, 501, 84, 74, 82, R.drawable.monster_v091_174),
            new Enemy("V091-175", "Poliarinis pasaulių ėdikas", "AUDRŲ ŠIAURĖ", "Pasaulio grėsmė", "pašvaistės blyksnis", "Audrų Šiaurės ledynuose sutinkamas priešas. Pavojingiausias jo bruožas – pašvaistės blyksnis; kovoje jis veikia kaip pasaulio grėsmė.", 10, 554, 82, 68, 94, R.drawable.monster_v091_175),
            new Enemy("V091-176", "Mutavusi kanalizacijos žiurkė", "LUMINAROS ŠEŠĖLIAI", "Medžiotojas", "pasalos žingsnis", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – pasalos žingsnis; kovoje jis veikia kaip medžiotojas.", 2, 179, 26, 23, 42, R.drawable.monster_v091_176),
            new Enemy("V091-177", "Skersgatvio gargulis", "LUMINAROS ŠEŠĖLIAI", "Persekiotojas", "kraujo ritualas", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – kraujo ritualas; kovoje jis veikia kaip persekiotojas.", 3, 232, 36, 32, 54, R.drawable.monster_v091_177),
            new Enemy("V091-178", "Maro kaukės kultistas", "LUMINAROS ŠEŠĖLIAI", "Sargas", "miesto reljefo išnaudojimas", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – miesto reljefo išnaudojimas; kovoje jis veikia kaip sargas.", 3, 243, 39, 35, 44, R.drawable.monster_v091_178),
            new Enemy("V091-179", "Gyvojo apsiausto vagis", "LUMINAROS ŠEŠĖLIAI", "Pasalūnas", "baimės aura", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – baimės aura; kovoje jis veikia kaip pasalūnas.", 4, 296, 49, 44, 56, R.drawable.monster_v091_179),
            new Enemy("V091-180", "Kraujo alchemikas", "LUMINAROS ŠEŠĖLIAI", "Ritualistas", "Meridiano kontrabanda", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – Meridiano kontrabanda; kovoje jis veikia kaip ritualistas.", 4, 307, 40, 32, 63, R.drawable.monster_v091_180),
            new Enemy("V091-181", "Kaukėtasis revenantas dvikovininkas", "LUMINAROS ŠEŠĖLIAI", "Žvalgas", "pasalos žingsnis", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – pasalos žingsnis; kovoje jis veikia kaip žvalgas.", 4, 263, 43, 35, 53, R.drawable.monster_v091_181),
            new Enemy("V091-182", "Monetų skrynios mimikas", "LUMINAROS ŠEŠĖLIAI", "Naikintojas", "kraujo ritualas", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – kraujo ritualas; kovoje jis veikia kaip naikintojas.", 5, 316, 53, 44, 65, R.drawable.monster_v091_182),
            new Enemy("V091-183", "Laikrodžio bokšto šikšnosparnis", "LUMINAROS ŠEŠĖLIAI", "Dvikovininkas", "miesto reljefo išnaudojimas", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – miesto reljefo išnaudojimas; kovoje jis veikia kaip dvikovininkas.", 5, 327, 56, 47, 55, R.drawable.monster_v091_183),
            new Enemy("V091-184", "Kanalizacijos krokodilas", "LUMINAROS ŠEŠĖLIAI", "Spąstų kūrėjas", "baimės aura", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – baimės aura; kovoje jis veikia kaip spąstų kūrėjas.", 5, 338, 47, 50, 62, R.drawable.monster_v091_184),
            new Enemy("V091-185", "Gildijos vykdytojo golemas", "LUMINAROS ŠEŠĖLIAI", "Smogikas", "Meridiano kontrabanda", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – Meridiano kontrabanda; kovoje jis veikia kaip smogikas.", 6, 391, 57, 44, 74, R.drawable.monster_v091_185),
            new Enemy("V091-186", "Raudonojo kulto kunigas", "LUMINAROS ŠEŠĖLIAI", "Teritorijos sargas", "pasalos žingsnis", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – pasalos žingsnis; kovoje jis veikia kaip teritorijos sargas.", 5, 305, 53, 41, 59, R.drawable.monster_v091_186),
            new Enemy("V091-187", "Šešėlių žudikas demonas", "LUMINAROS ŠEŠĖLIAI", "Skrendantis medžiotojas", "kraujo ritualas", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – kraujo ritualas; kovoje jis veikia kaip skrendantis medžiotojas.", 6, 358, 63, 50, 71, R.drawable.monster_v091_187),
            new Enemy("V091-188", "Apsėsta marmuro statula", "LUMINAROS ŠEŠĖLIAI", "Silpnintojas", "miesto reljefo išnaudojimas", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – miesto reljefo išnaudojimas; kovoje jis veikia kaip silpnintojas.", 6, 369, 54, 53, 61, R.drawable.monster_v091_188),
            new Enemy("V091-189", "Grandinėtas ogras", "LUMINAROS ŠEŠĖLIAI", "Pramušėjas", "baimės aura", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – baimės aura; kovoje jis veikia kaip pramušėjas.", 6, 380, 57, 56, 68, R.drawable.monster_v091_189),
            new Enemy("V091-190", "Žvakių liepsnos šmėkla", "LUMINAROS ŠEŠĖLIAI", "Kontrolierius", "Meridiano kontrabanda", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – Meridiano kontrabanda; kovoje jis veikia kaip kontrolierius.", 7, 433, 67, 50, 63, R.drawable.monster_v091_190),
            new Enemy("V091-191", "Rūmų veidrodžio demonas", "LUMINAROS ŠEŠĖLIAI", "Burtininkas", "pasalos žingsnis", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – pasalos žingsnis; kovoje jis veikia kaip burtininkas.", 6, 347, 63, 47, 65, R.drawable.monster_v091_191),
            new Enemy("V091-192", "Varpinės šmėkla", "LUMINAROS ŠEŠĖLIAI", "Greitas puolėjas", "kraujo ritualas", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – kraujo ritualas; kovoje jis veikia kaip greitas puolėjas.", 7, 400, 61, 56, 77, R.drawable.monster_v091_192),
            new Enemy("V091-193", "Gyvojo rašalo siaubūnas", "LUMINAROS ŠEŠĖLIAI", "Aukštumų sargas", "miesto reljefo išnaudojimas", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – miesto reljefo išnaudojimas; kovoje jis veikia kaip aukštumų sargas.", 7, 411, 64, 59, 67, R.drawable.monster_v091_193),
            new Enemy("V091-194", "Teismo egzekutorius", "LUMINAROS ŠEŠĖLIAI", "Minios laužytojas", "baimės aura", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – baimės aura; kovoje jis veikia kaip minios laužytojas.", 7, 422, 67, 62, 74, R.drawable.monster_v091_194),
            new Enemy("V091-195", "Katakombų vampyrų valdovas", "LUMINAROS ŠEŠĖLIAI", "Nuodytojas", "Meridiano kontrabanda", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – Meridiano kontrabanda; kovoje jis veikia kaip nuodytojas.", 8, 475, 77, 56, 69, R.drawable.monster_v091_195),
            new Enemy("V091-196", "Kaukėtasis kulto hierofantas", "LUMINAROS ŠEŠĖLIAI", "Elitinis sargas", "pasalos žingsnis", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – pasalos žingsnis; kovoje jis veikia kaip elitinis sargas.", 8, 431, 68, 59, 76, R.drawable.monster_v091_196),
            new Enemy("V091-197", "Miesto rijikas", "LUMINAROS ŠEŠĖLIAI", "Atgimstantis plėšrūnas", "kraujo ritualas", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – kraujo ritualas; kovoje jis veikia kaip atgimstantis plėšrūnas.", 8, 442, 71, 62, 83, R.drawable.monster_v091_197),
            new Enemy("V091-198", "Kruvinasis puolęs angelas", "LUMINAROS ŠEŠĖLIAI", "Būrio vadas", "miesto reljefo išnaudojimas", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – miesto reljefo išnaudojimas; kovoje jis veikia kaip būrio vadas.", 9, 495, 81, 71, 78, R.drawable.monster_v091_198),
            new Enemy("V091-199", "Senasis Meridiano vartų globėjas", "LUMINAROS ŠEŠĖLIAI", "Senovinis globėjas", "baimės aura", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – baimės aura; kovoje jis veikia kaip senovinis globėjas.", 9, 506, 84, 74, 85, R.drawable.monster_v091_199),
            new Enemy("V091-200", "Užtemimo drakonas", "LUMINAROS ŠEŠĖLIAI", "Pasaulio grėsmė", "Meridiano kontrabanda", "Luminaros požemiuose ir užtemusiuose kvartaluose sutinkamas priešas. Pavojingiausias jo bruožas – Meridiano kontrabanda; kovoje jis veikia kaip pasaulio grėsmė.", 10, 559, 82, 68, 80, R.drawable.monster_v091_200)
    };

    private static final Map<String, Enemy> BY_NAME = new HashMap<>();

    static {
        for (Enemy enemy : ALL) BY_NAME.put(normalize(enemy.name), enemy);
    }

    private EnemyCatalogV091() {}

    static String[] regions() { return REGIONS.clone(); }

    static List<Enemy> inRegion(String region) {
        ArrayList<Enemy> result = new ArrayList<>();
        for (Enemy enemy : ALL) if (enemy.region.equals(region)) result.add(enemy);
        return result;
    }

    static Enemy find(String value) {
        String query = normalize(value);
        Enemy exact = BY_NAME.get(query);
        if (exact != null || query.length() < 4) return exact;
        for (Enemy enemy : ALL) {
            String key = normalize(enemy.name);
            if (query.contains(key) || (query.length() >= 8 && key.contains(query))) return enemy;
            String stem = key.length() > 10 ? key.substring(0, key.length() - 2) : key;
            if (query.contains(stem)) return enemy;
        }
        return null;
    }

    static int artFor(String name) {
        Enemy enemy = find(name);
        return enemy == null ? 0 : enemy.artwork;
    }

    static Enemy encounterFor(String location, long seed) {
        String region = regionForLocation(location, seed);
        List<Enemy> candidates = inRegion(region);
        int safePool = Math.min(20, candidates.size());
        int index = (int) Math.floorMod(seed, safePool);
        return candidates.get(index);
    }

    static String promptRoster() {
        StringBuilder result = new StringBuilder();
        for (int index = 0; index < ALL.length; index++) {
            if (index > 0) result.append(", ");
            result.append(ALL[index].name);
        }
        return result.toString();
    }

    private static String regionForLocation(String location, long seed) {
        String query = normalize(location);
        if (containsAny(query, "pelkyn", "labirint", "giria", "misk", "stiklo")) return REGIONS[1];
        if (containsAny(query, "kaln", "kharad", "veyrhold", "asterio", "virsun")) return REGIONS[2];
        if (containsAny(query, "meridian", "vart", "anomal", "orison", "tustum")) return REGIONS[3];
        if (containsAny(query, "dirbtuv", "griuv", "tiglio", "forge")) return REGIONS[4];
        if (containsAny(query, "pakrant", "jura", "safyro", "bedugn", "rif")) return REGIONS[5];
        if (containsAny(query, "siaur", "led", "salc", "audr")) return REGIONS[6];
        if (containsAny(query, "luminara", "miest", "rum", "turgaus")) return REGIONS[7];
        return REGIONS[(int) Math.floorMod(seed, REGIONS.length)];
    }

    private static String normalize(String value) {
        String lower = value == null ? "" : value.toLowerCase(Locale.forLanguageTag("lt-LT"));
        return Normalizer.normalize(lower, Normalizer.Form.NFD)
                .replaceAll("\\p{M}+", "")
                .replace('’', '\'')
                .trim();
    }

    private static boolean containsAny(String value, String... needles) {
        for (String needle : needles) if (value.contains(needle)) return true;
        return false;
    }
}
