package lt.vaeloria.ooc;

import android.content.Context;
import android.graphics.*;
import android.view.*;
import java.util.*;

/** Vaeloria v0.8.2 premium visual components. Bundled/offline only. */
class SceneV082View extends View {
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);
    final Bitmap palace,city,wild;
    String location="Luminara",scene="";
    SceneV082View(Context c){
        super(c);setLayerType(LAYER_TYPE_SOFTWARE,null);
        palace=BitmapFactory.decodeResource(getResources(),R.drawable.scene_palace_v083);
        city=BitmapFactory.decodeResource(getResources(),R.drawable.scene_luminara);
        wild=BitmapFactory.decodeResource(getResources(),R.drawable.combat_forest);
    }
    void setScene(String l,String s){location=l==null?"Luminara":l;scene=s==null?"":s;invalidate();}
    protected void onDraw(Canvas c){
        int w=getWidth(),h=getHeight();String q=(location+" "+scene).toLowerCase(Locale.ROOT);
        Bitmap b=(q.contains("rūm")||q.contains("rum")||q.contains("salė")||q.contains("sale")||q.contains("sarg")||q.contains("slapt"))?palace:(q.contains("luminara")?city:wild);
        cover(c,b,w,h);
        p.setShader(new LinearGradient(0,0,0,h,new int[]{Color.argb(8,0,0,0),Color.argb(28,0,0,0),Color.argb(232,2,7,11)},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);
        p.setColor(Color.argb(170,3,9,14));c.drawRoundRect(new RectF(dp(12),dp(12),dp(126),dp(39)),dp(14),dp(14),p);
        p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(8));p.setColor(Color.rgb(221,187,104));c.drawText("GYVA SCENA",dp(26),dp(30),p);
        p.setTypeface(Typeface.create(Typeface.SERIF,Typeface.BOLD));int size=25;String title=location.toUpperCase(Locale.forLanguageTag("lt-LT"));p.setTextSize(dp(size));while(size>15&&p.measureText(title)>w-dp(32)){size--;p.setTextSize(dp(size));}
        p.setColor(Color.rgb(245,229,194));p.setShadowLayer(dp(5),0,2,Color.BLACK);c.drawText(title,dp(16),h-dp(45),p);p.clearShadowLayer();
        p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(10));p.setColor(Color.rgb(197,209,209));c.drawText(trim(scene,54),dp(17),h-dp(21),p);
    }
    void cover(Canvas c,Bitmap b,int w,int h){if(b==null)return;float s=Math.max(w/(float)b.getWidth(),h/(float)b.getHeight());int sw=Math.round(w/s),sh=Math.round(h/s),l=Math.max(0,(b.getWidth()-sw)/2),t=Math.max(0,(b.getHeight()-sh)/2);c.drawBitmap(b,new Rect(l,t,Math.min(b.getWidth(),l+sw),Math.min(b.getHeight(),t+sh)),new RectF(0,0,w,h),p);}
    String trim(String s,int n){return s==null?"":s.length()>n?s.substring(0,n-1)+"…":s;}
    int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

class WorldMapV082View extends View {
    interface Listener{void onLocationSelected(String name,int danger);}
    static final class N{final String name,type;final float x,y;final int danger;N(String n,float x,float y,int d,String t){name=n;this.x=x;this.y=y;danger=d;type=t;}}
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);final Bitmap map;final ArrayList<N> ns=new ArrayList<>();final ScaleGestureDetector scaleDetector;final GestureDetector gestures;
    Listener listener;String current="Luminara",selected="";float base=1,zoom=1,tx,ty,lastX,lastY;boolean drag,showFactions=false;
    WorldMapV082View(Context c){
        super(c);setBackgroundColor(Color.rgb(3,8,13));setLayerType(LAYER_TYPE_SOFTWARE,null);map=BitmapFactory.decodeResource(getResources(),R.drawable.world_map_v083);
        add("Luminara",215,340,3,"capital");add("Asterio Karūna",120,115,4,"fortress");add("Stiklo Giria",225,170,5,"anomaly");add("Veyrhold",325,300,3,"city");add("Aureliono Pakraštys",325,455,4,"gate");add("Žvaigždėkritos Skliautas",280,430,7,"anomaly");add("Tuščiavidurė Smailė",72,470,8,"dungeon");add("Pelenų Karūnos Citadelė",450,250,7,"fortress");add("Kharad Vorn",505,335,5,"city");add("Drakono Pabudimo Viršūnės",510,130,8,"anomaly");add("Safyro Platybės",450,555,7,"unknown");add("Amžinojo Šaltinio Slėnis",400,690,4,"temple");add("Žaliasis Labirintas",470,805,8,"dungeon");add("Šventųjų Pelkynas",290,865,6,"unknown");
        scaleDetector=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){float before=base*zoom,mx=(d.getFocusX()-tx)/before,my=(d.getFocusY()-ty)/before;zoom=Math.max(1,Math.min(4.2f,zoom*d.getScaleFactor()));float after=base*zoom;tx=d.getFocusX()-mx*after;ty=d.getFocusY()-my*after;clamp();invalidate();return true;}});
        gestures=new GestureDetector(c,new GestureDetector.SimpleOnGestureListener(){public boolean onDoubleTap(MotionEvent e){if(zoom>1.1f)resetView();else zoomAt(e.getX(),e.getY(),2.15f);return true;}});
    }
    void add(String n,float x,float y,int d,String t){ns.add(new N(n,x,y,d,t));}void setListener(Listener l){listener=l;}void setCurrentLocation(String s){current=s==null?"Luminara":s;invalidate();}void toggleFactions(){showFactions=!showFactions;invalidate();}
    N find(String s){if(s==null)return null;for(N n:ns)if(n.name.equalsIgnoreCase(s)||aliases(n.name,s))return n;String q=s.toLowerCase(Locale.ROOT);if(q.contains("luminara")||q.contains("rūm")||q.contains("rum")||q.contains("miesto "))return direct("Luminara");return null;}
    N direct(String s){for(N n:ns)if(n.name.equals(s))return n;return null;}
    boolean aliases(String a,String b){String q=b.toLowerCase(Locale.ROOT);return(a.startsWith("Asterio")&&q.contains("crown"))||(a.startsWith("Stiklo")&&q.contains("glass"))||(a.startsWith("Aureliono")&&q.contains("aurel"))||(a.startsWith("Žvaigždė")&&q.contains("star"))||(a.startsWith("Tuščiavidurė")&&q.contains("hollow"))||(a.startsWith("Pelenų")&&q.contains("ashen"))||(a.startsWith("Drakono")&&q.contains("dragon"))||(a.startsWith("Safyro")&&q.contains("sapphire"))||(a.startsWith("Amžinojo")&&q.contains("spring"))||(a.startsWith("Šventųjų")&&q.contains("mire"))||(a.startsWith("Žaliasis")&&q.contains("verdant"));}
    protected void onSizeChanged(int w,int h,int ow,int oh){resetView();}
    void resetView(){if(map==null||getWidth()==0||getHeight()==0)return;base=Math.min(getWidth()/(float)map.getWidth(),getHeight()/(float)map.getHeight());if(base<=0)base=1;zoom=1;N n=find(current);float s=base;tx=getWidth()/2f-(n==null?map.getWidth()/2f:n.x)*s;ty=getHeight()/2f-(n==null?map.getHeight()/2f:n.y)*s;clamp();invalidate();}
    protected void onDraw(Canvas c){super.onDraw(c);if(map==null)return;float s=base*zoom;c.save();c.translate(tx,ty);c.scale(s,s);c.drawBitmap(map,0,0,p);if(showFactions)drawFactions(c);float inv=1/s;for(N n:ns)drawNode(c,n,inv,n==find(current),n.name.equals(selected));c.restore();if(isAttachedToWindow())postInvalidateDelayed(70);}
    void drawFactions(Canvas c){p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(20,92,142,188));Path a=new Path();a.moveTo(22,70);a.lineTo(330,70);a.lineTo(360,470);a.lineTo(180,600);a.lineTo(20,500);a.close();c.drawPath(a,p);p.setColor(Color.argb(20,203,92,65));Path d=new Path();d.moveTo(330,40);d.lineTo(585,40);d.lineTo(580,500);d.lineTo(360,470);d.close();c.drawPath(d,p);p.setColor(Color.argb(20,112,171,95));Path l=new Path();l.moveTo(170,500);l.lineTo(580,480);l.lineTo(570,915);l.lineTo(130,915);l.close();c.drawPath(l,p);}
    void drawNode(Canvas c,N n,float inv,boolean here,boolean sel){int col=dangerColor(n.danger);float r=6*inv;p.setStrokeWidth(2.1f*inv);p.setStyle(Paint.Style.STROKE);p.setColor(col);float x=n.x,y=n.y;if("capital".equals(n.type)){Path q=new Path();q.moveTo(x,y-9*inv);q.lineTo(x+9*inv,y);q.lineTo(x,y+9*inv);q.lineTo(x-9*inv,y);q.close();c.drawPath(q,p);c.drawCircle(x,y,2.4f*inv,p);}else if("fortress".equals(n.type)){c.drawRect(x-7*inv,y-7*inv,x+7*inv,y+7*inv,p);c.drawLine(x-7*inv,y-7*inv,x,y-12*inv,p);c.drawLine(x,y-12*inv,x+7*inv,y-7*inv,p);}else if("dungeon".equals(n.type)){Path q=new Path();q.moveTo(x,y-9*inv);q.lineTo(x+8*inv,y+7*inv);q.lineTo(x-8*inv,y+7*inv);q.close();c.drawPath(q,p);}else if("temple".equals(n.type)){c.drawCircle(x,y,8*inv,p);c.drawCircle(x,y,3*inv,p);}else if("gate".equals(n.type)){c.drawCircle(x,y,8*inv,p);c.drawLine(x,y-8*inv,x,y+8*inv,p);}else if("anomaly".equals(n.type)){c.drawCircle(x,y,8*inv,p);c.drawLine(x-7*inv,y,x+7*inv,y,p);c.drawLine(x,y-7*inv,x,y+7*inv,p);}else c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(224,3,9,13));p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(7)*inv);float tw=p.measureText(n.name),pad=4*inv,lh=13*inv;float lx=x+11*inv,ly=y-9*inv;if(lx+tw+pad*2>map.getWidth())lx=x-tw-pad*2-11*inv;c.drawRoundRect(lx-pad,ly-lh*.65f,lx+tw+pad,ly+lh*.45f,4*inv,4*inv,p);p.setColor(Color.rgb(235,230,214));c.drawText(n.name,lx,ly,p);if(here){float pulse=(System.currentTimeMillis()%1600)/1600f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3*inv);p.setColor(Color.argb((int)(210*(1-pulse)),244,204,103));c.drawCircle(x,y,(14+23*pulse)*inv,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(244,204,103));c.drawCircle(x,y,4.5f*inv,p);}if(sel){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2.5f*inv);p.setColor(Color.rgb(92,190,178));c.drawCircle(x,y,15*inv,p);p.setStyle(Paint.Style.FILL);}}
    int dangerColor(int d){return d>=8?Color.rgb(219,86,75):d>=6?Color.rgb(219,145,74):d>=4?Color.rgb(219,187,104):Color.rgb(92,184,174);}
    public boolean onTouchEvent(MotionEvent e){gestures.onTouchEvent(e);scaleDetector.onTouchEvent(e);switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:getParent().requestDisallowInterceptTouchEvent(true);lastX=e.getX();lastY=e.getY();drag=false;return true;case MotionEvent.ACTION_MOVE:if(!scaleDetector.isInProgress()){float dx=e.getX()-lastX,dy=e.getY()-lastY;if(Math.abs(dx)+Math.abs(dy)>6)drag=true;tx+=dx;ty+=dy;lastX=e.getX();lastY=e.getY();clamp();invalidate();}return true;case MotionEvent.ACTION_UP:if(!drag)select(e.getX(),e.getY());getParent().requestDisallowInterceptTouchEvent(false);return true;case MotionEvent.ACTION_CANCEL:getParent().requestDisallowInterceptTouchEvent(false);return true;}return true;}
    void select(float sx,float sy){float s=base*zoom,mx=(sx-tx)/s,my=(sy-ty)/s;N best=null;float bd=Float.MAX_VALUE;for(N n:ns){float dx=n.x-mx,dy=n.y-my,d=dx*dx+dy*dy;if(d<bd){bd=d;best=n;}}if(best!=null&&bd<62*62){selected=best.name;performClick();invalidate();if(listener!=null)listener.onLocationSelected(best.name,best.danger);}}
    public boolean performClick(){super.performClick();return true;}void zoomAt(float x,float y,float z){float before=base*zoom,mx=(x-tx)/before,my=(y-ty)/before;zoom=z;float after=base*zoom;tx=x-mx*after;ty=y-my*after;clamp();invalidate();}
    void clamp(){if(map==null)return;float sw=map.getWidth()*base*zoom,sh=map.getHeight()*base*zoom,m=dp(36);tx=sw<=getWidth()?(getWidth()-sw)/2:Math.max(getWidth()-sw-m,Math.min(m,tx));ty=sh<=getHeight()?(getHeight()-sh)/2:Math.max(getHeight()-sh-m,Math.min(m,ty));}
    int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

class LoadoutV082View extends View {
    interface Listener{void onSlotPressed(String slot);}static final class S{String title,item,rarity;int col;S(String t,String i,String r,int c){title=t;item=i;rarity=r;col=c;}}
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);final Bitmap hero;final LinkedHashMap<String,S> slots=new LinkedHashMap<>();final LinkedHashMap<String,RectF> hits=new LinkedHashMap<>();Listener listener;
    LoadoutV082View(Context c){super(c);setLayerType(LAYER_TYPE_SOFTWARE,null);hero=BitmapFactory.decodeResource(getResources(),R.drawable.hero_einoras_v083);}void setListener(Listener l){listener=l;}void put(String k,String t,String i,String rarity,int col){slots.put(k,new S(t,i,rarity,col));invalidate();}
    protected void onDraw(Canvas c){hits.clear();int w=getWidth(),h=getHeight();p.setShader(new LinearGradient(0,0,0,h,Color.rgb(6,15,22),Color.rgb(3,8,13),Shader.TileMode.CLAMP));c.drawRoundRect(0,0,w,h,dp(18),dp(18),p);p.setShader(null);if(hero!=null){Rect src=new Rect(0,0,hero.getWidth(),hero.getHeight());RectF dst=new RectF(w*.23f,dp(10),w*.77f,h-dp(62));c.drawBitmap(hero,src,dst,p);}float bw=Math.min(dp(108),w*.29f),bh=dp(44),y=dp(28);String[] ks={"head","neck","weapon","offhand","chest","utility","hands","belt","legs","feet","ring_left","ring_right"};for(int i=0;i<ks.length;i+=2){slot(c,ks[i],dp(8),y,bw,bh);slot(c,ks[i+1],w-bw-dp(8),y,bw,bh);y+=dp(51);}String[] rs={"relic_1","relic_2","relic_3","relic_4"};float gap=dp(5),rw=(w-dp(18)-gap*3)/4f,ry=h-dp(54);for(int i=0;i<4;i++)slot(c,rs[i],dp(9)+i*(rw+gap),ry,rw,dp(44));}
    void slot(Canvas c,String k,float x,float y,float w,float h){S s=slots.get(k);boolean eq=s!=null&&s.item!=null&&!s.item.isEmpty();int col=eq?s.col:Color.rgb(54,70,78);RectF r=new RectF(x,y,x+w,y+h);hits.put(k,r);p.setColor(Color.argb(eq?226:190,5,14,20));c.drawRoundRect(r,dp(10),dp(10),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(eq?dp(1.5f):dp(1));p.setColor(col);c.drawRoundRect(r,dp(10),dp(10),p);p.setStyle(Paint.Style.FILL);float ix=x+dp(13),iy=y+h/2;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1.5f));p.setColor(col);c.drawCircle(ix,iy,dp(7),p);if(eq){c.drawLine(ix-dp(4),iy+dp(4),ix+dp(4),iy-dp(4),p);}p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(6.2f));p.setColor(col);String title=s==null?k:s.title;c.drawText(fit(title.toUpperCase(Locale.ROOT),w-dp(34)),x+dp(25),y+dp(14),p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(dp(7.2f));p.setColor(eq?Color.rgb(235,233,222):Color.rgb(104,120,128));c.drawText(fit(eq?s.item:"Tuščia",w-dp(34)),x+dp(25),y+dp(32),p);}
    String fit(String s,float m){if(p.measureText(s)<=m)return s;String x=s;while(x.length()>2&&p.measureText(x+"…")>m)x=x.substring(0,x.length()-1);return x+"…";}
    public boolean onTouchEvent(MotionEvent e){if(e.getActionMasked()==MotionEvent.ACTION_UP)for(Map.Entry<String,RectF> q:hits.entrySet())if(q.getValue().contains(e.getX(),e.getY())){performClick();if(listener!=null)listener.onSlotPressed(q.getKey());return true;}return true;}public boolean performClick(){super.performClick();return true;}int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

class FactionStatusV082View extends View {
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);final GameState state;
    FactionStatusV082View(Context c,GameState s){super(c);state=s;}
    protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setColor(Color.rgb(8,18,25));c.drawRoundRect(0,0,w,h,dp(16),dp(16),p);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(8));p.setColor(Color.rgb(221,187,104));c.drawText("PASAULIO BŪSENA · MERIDIANO KRIZĖ",dp(13),dp(22),p);String[] n={"ASTERRA","DRAVENN","LYSARA"},r={state.asterraRelation,state.dravennRelation,state.lysaraRelation};int[] col={Color.rgb(111,156,198),Color.rgb(206,101,69),Color.rgb(120,174,99)},val={state.asterraInfluence,state.dravennInfluence,state.lysaraInfluence};float gap=dp(7),cw=(w-dp(26)-gap*2)/3f;for(int i=0;i<3;i++){float x=dp(13)+i*(cw+gap),y=dp(35);RectF card=new RectF(x,y,x+cw,h-dp(10));p.setColor(Color.rgb(11,24,31));c.drawRoundRect(card,dp(12),dp(12),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(Color.argb(150,Color.red(col[i]),Color.green(col[i]),Color.blue(col[i])));c.drawRoundRect(card,dp(12),dp(12),p);p.setStyle(Paint.Style.FILL);float cx=x+cw/2,cy=y+dp(28);p.setColor(Color.argb(38,Color.red(col[i]),Color.green(col[i]),Color.blue(col[i])));c.drawCircle(cx,cy,dp(19),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(2));p.setColor(col[i]);emblem(c,i,cx,cy);p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.create(Typeface.SERIF,Typeface.BOLD));p.setTextSize(dp(8));p.setColor(Color.rgb(235,223,193));float tw=p.measureText(n[i]);c.drawText(n[i],cx-tw/2,y+dp(57),p);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(6.5f));p.setColor(col[i]);tw=p.measureText(r[i]);c.drawText(r[i],cx-tw/2,y+dp(72),p);float by=y+dp(83);p.setColor(Color.rgb(29,41,47));c.drawRoundRect(x+dp(8),by,x+cw-dp(8),by+dp(5),dp(3),dp(3),p);p.setColor(col[i]);c.drawRoundRect(x+dp(8),by,x+dp(8)+(cw-dp(16))*val[i]/100f,by+dp(5),dp(3),dp(3),p);p.setTextSize(dp(6));p.setColor(Color.rgb(145,163,168));String cap="ĮTAKA "+val[i];tw=p.measureText(cap);c.drawText(cap,cx-tw/2,by+dp(15),p);}}
    void emblem(Canvas c,int i,float x,float y){if(i==0){Path q=new Path();for(int k=0;k<8;k++){double a=-Math.PI/2+k*Math.PI/4;float rr=dp(k%2==0?14:6);float px=x+(float)Math.cos(a)*rr,py=y+(float)Math.sin(a)*rr;if(k==0)q.moveTo(px,py);else q.lineTo(px,py);}q.close();c.drawPath(q,p);c.drawCircle(x,y,dp(3),p);}else if(i==1){Path q=new Path();q.moveTo(x,y-dp(15));q.lineTo(x+dp(10),y-dp(4));q.lineTo(x+dp(5),y+dp(15));q.lineTo(x,y+dp(7));q.lineTo(x-dp(6),y+dp(15));q.lineTo(x-dp(11),y-dp(4));q.close();c.drawPath(q,p);c.drawLine(x,y-dp(10),x,y+dp(9),p);}else{Path q=new Path();q.moveTo(x,y-dp(15));q.cubicTo(x+dp(17),y-dp(8),x+dp(14),y+dp(12),x,y+dp(15));q.cubicTo(x-dp(14),y+dp(12),x-dp(17),y-dp(8),x,y-dp(15));c.drawPath(q,p);c.drawLine(x,y-dp(10),x,y+dp(12),p);}}
    int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

