package lt.vaeloria.ooc;

import android.app.*;
import android.content.*;
import android.content.res.ColorStateList;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;

public class PremiumActivity extends VaeloriaActivity {
    static final int INK=Color.rgb(4,11,16),PANEL=Color.rgb(10,20,27),PANEL2=Color.rgb(14,27,35),PARCH=Color.rgb(241,226,190),SUB=Color.rgb(158,176,181),GOLD2=Color.rgb(221,187,104),TEAL2=Color.rgb(92,184,174);
    ToneGenerator tone;VaeloriaAudio audio;
    static final String[][] NPCS={{"Lyra Fen","Juvelyrė ir maginių fokusų meistrė","Kurti patikimus fokusus ir stabdyti netikrų brangakmenių srautą."},{"Oren Vale","Rezonanso tyrėjas","Tyrinėti rezonansą neaukojant saugumo ir nepriklausomo sprendimo."},{"Mara Vell","Prekybininkė ir tiekimo tarpininkė","Išlaikyti patikimą prekių srautą tarp gildijų, keliautojų ir gyventojų."},{"Nessa Vale","Apsauginių audinių meistrė","Kurti keliautojams prieinamą apsauginę aprangą maginei aplinkai."},{"Aven Rusk","Alchemikas","Legaliai gauti retus reagentus ir neleisti pavojingoms medžiagoms patekti į neatsakingas rankas."},{"Sera Halden","Gydytoja","Išlaikyti prieinamą kliniką ir dokumentuoti neįprastas magines traumas."}};

    @Override public void onCreate(Bundle stateBundle){super.onCreate(stateBundle);audio=new VaeloriaAudio(this);audio.startAmbient(state.location);}
    @Override protected void onResume(){super.onResume();if(audio!=null&&state!=null)audio.startAmbient(state.location);}
    @Override protected void onPause(){if(audio!=null)audio.stopAmbient();super.onPause();}

    @Override void shell(){
        root=col();root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{Color.rgb(3,9,13),Color.rgb(6,15,21),Color.rgb(3,9,13)}));
        root.setOnApplyWindowInsetsListener((v,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars());top=bars.top;bottom=bars.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return insets;});
        LinearLayout top=row();top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(18),0,dp(14),0);top.setBackgroundColor(Color.rgb(4,12,17));TextView brand=serif("VAELORIA",26,GOLD2,true);brand.setLetterSpacing(.06f);top.addView(brand,new LinearLayout.LayoutParams(0,dp(60),1));LinearLayout loc=col();loc.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);TextView l=txt(state.location.toUpperCase(Locale.forLanguageTag("lt-LT")),9,PARCH,true);l.setGravity(Gravity.END);TextView y=txt("METAI "+state.worldYear,8,SUB,false);y.setGravity(Gravity.END);loc.addView(l);loc.addView(y);top.addView(loc,new LinearLayout.LayoutParams(dp(155),dp(60)));root.addView(top,new LinearLayout.LayoutParams(-1,dp(60)));
        content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav=row();nav.setPadding(dp(4),dp(3),dp(4),dp(4));nav.setBackgroundColor(Color.rgb(4,12,17));root.addView(nav,new LinearLayout.LayoutParams(-1,dp(74)));setContentView(root);root.requestApplyInsets();
    }
    @Override void nav(){nav.removeAllViews();tab2("game","game","ŽAISTI");tab2("hero","hero","VEIKĖJAS");tab2("map","map","ŽEMĖLAPIS");tab2("journal","journal","ŽURNALAS");tab2("settings","settings","NUSTAT.");}
    void tab2(String id,String glyph,String label){LinearLayout x=col();x.setGravity(Gravity.CENTER);boolean a=id.equals(screen);if(a)x.setBackground(round(Color.rgb(20,31,37),16,Color.argb(145,221,187,104)));NavGlyphView g=new NavGlyphView(this,glyph);g.setActive(a);x.addView(g,new LinearLayout.LayoutParams(dp(30),dp(30)));TextView t=txt(label,8,a?PARCH:Color.rgb(143,160,165),true);t.setGravity(Gravity.CENTER);x.addView(t);x.setOnClickListener(v->{haptic();sound(false);show(id);});nav.addView(x,new LinearLayout.LayoutParams(0,-1,1));}
    @Override void show(String id){screen=id;nav();content.removeAllViews();View v;try{v="game".equals(id)?game():"hero".equals(id)?hero():"map".equals(id)?map():"journal".equals(id)?journal():settings();}catch(Throwable e){v=errorView(e);}content.addView(v);if(pref("animations",true)){v.setAlpha(0);v.setTranslationY(dp(8));v.animate().alpha(1).translationY(0).setDuration(180).start();}}

    @Override View game(){
        ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(10),dp(6),dp(10),dp(18));sv.addView(c);
        if(state.combatActive){CombatBoardView b=new CombatBoardView(this);b.setState(state);c.addView(b,new LinearLayout.LayoutParams(-1,dp(300)));}else{SceneBannerView art=new SceneBannerView(this);art.setScene(state.location,state.sceneTitle,"",state.worldMinute);c.addView(art,new LinearLayout.LayoutParams(-1,dp(245)));}
        c.addView(resources(),sp(dp(8)));if(!feedback.isEmpty()){TextView f=txt(feedback,10,Color.rgb(214,229,221),true);f.setPadding(dp(11),dp(8),dp(11),dp(8));f.setBackground(round(Color.rgb(14,38,37),12,Color.argb(120,92,184,174)));c.addView(f,sp(dp(8)));}
        LinearLayout story=surface(true);story.addView(section("AKTYVI SCENA"));story.addView(serif(state.sceneTitle,24,PARCH,true),sp(dp(5)));TextView body=txt(state.scene,14,Color.rgb(222,226,220),false);body.setLineSpacing(dp(2),1.08f);story.addView(body);c.addView(story,sp(dp(10)));
        LinearLayout q=surface(false);q.addView(section("PAGRINDINĖ UŽDUOTIS"));q.addView(serif(state.questTitle,17,PARCH,true));q.addView(txt(state.objective,10,SUB,false));q.setOnClickListener(v->show("journal"));c.addView(q,sp(dp(10)));
        c.addView(section("KĄ DARAI?"),sp(dp(6)));for(int i=0;i<Math.min(3,state.choices.size());i++){String a=state.choices.get(i);c.addView(choice(i+1,a),sp(dp(6)));}
        if(!state.combatActive){Button explore=outline("TYRINĖTI "+state.location.toUpperCase(Locale.forLanguageTag("lt-LT")));explore.setOnClickListener(v->{haptic();locationHub();});c.addView(explore,sp(dp(9)));}
        LinearLayout free=surface(false);free.addView(section("LAISVAS VEIKSMAS"));EditText in=new EditText(this);in.setHint("Aprašyk bet kokį veiksmą…");in.setHintTextColor(Color.rgb(105,125,132));in.setTextColor(Color.rgb(236,237,230));in.setTextSize(13);in.setMinLines(2);in.setMaxLines(4);in.setPadding(dp(11),dp(9),dp(11),dp(9));in.setBackground(round(Color.rgb(7,16,22),12,Color.rgb(41,61,70)));free.addView(in,sp(dp(7)));Button send=gold(busy?"SPRENDŽIAMA…":"ATLIKTI VEIKSMĄ");send.setEnabled(!busy);send.setOnClickListener(v->{String a=in.getText().toString().trim();if(!a.isEmpty())act(a);});free.addView(send);c.addView(free);return sv;
    }

    @Override View hero(){
        ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(10),dp(6),dp(10),dp(20));sv.addView(c);FrameLayout h=new FrameLayout(this);ImageView art=image(R.drawable.hero_einoras_v090);h.addView(art,new FrameLayout.LayoutParams(-1,dp(340)));View shade=new View(this);shade.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{Color.argb(0,0,0,0),Color.argb(235,3,9,13)}));h.addView(shade,new FrameLayout.LayoutParams(-1,dp(340)));LinearLayout ov=col();ov.setPadding(dp(16),0,dp(16),dp(15));ov.addView(serif(state.characterName.toUpperCase(Locale.forLanguageTag("lt-LT")),28,PARCH,true));ov.addView(txt(CharacterCatalogV093.ageLine(state),10,SUB,false));ov.addView(txt("legendary".equals(state.progressionMode)?"92 / 92 bazinės savybės · 100/100":"LYGIS "+state.level+" · SUBALANSUOTA PROGRESIJA",10,GOLD2,true));h.addView(ov,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));c.addView(h,new LinearLayout.LayoutParams(-1,dp(340)));c.addView(resources(),sp(dp(8)));
        CharacterLoadoutView load=new CharacterLoadoutView(this);String[] slots={"head","neck","weapon","offhand","chest","utility","hands","belt","legs","feet","ring_left","ring_right","relic_1","relic_2","relic_3","relic_4"};for(String s:slots){VaeloriaDb.Item it=db.getEquippedAt(s);load.put(s,VaeloriaDb.slotLabel(s),it==null?"":it.name,it==null?Color.rgb(70,88,96):rarity(it.rarity));}load.setListener(this::openSlot);c.addView(load,new LinearLayout.LayoutParams(-1,dp(545)));
        LinearLayout inv=surface(true);inv.addView(section("INVENTORIUS"));List<VaeloriaDb.Item> items=db.getItems();for(int i=0;i<items.size();i+=4){LinearLayout r=row();for(int j=0;j<4;j++){if(i+j<items.size()){VaeloriaDb.Item it=items.get(i+j);r.addView(itemTile(it),new LinearLayout.LayoutParams(0,dp(102),1));}else r.addView(new View(this),new LinearLayout.LayoutParams(0,dp(102),1));}inv.addView(r);}c.addView(inv,sp(dp(9)));
        LinearLayout ab=surface(false);ab.addView(section("MEISTRIŠKUMAS IR GEBĖJIMAI"));for(String[] a:db.getAbilities()){ab.addView(txt("◆  "+a[0],11,PARCH,true),sp(dp(2)));ab.addView(txt(abilityType(a[1])+" · "+a[2],9,SUB,false),sp(dp(6)));}c.addView(ab);return sv;
    }

    @Override View map(){FrameLayout f=new FrameLayout(this);WorldMapView world=new WorldMapView(this);world.setCurrentLocation(state.location);world.setListener(this::locationDialog);f.addView(world,new FrameLayout.LayoutParams(-1,-1));LinearLayout top=surface(false);top.addView(section("PASAULIO ATLASAS"));top.addView(serif(state.location,18,PARCH,true));top.addView(txt("Žnybk · tempk · dukart bakstelėk · paliesk vietą",9,SUB,false));FrameLayout.LayoutParams tp=new FrameLayout.LayoutParams(-1,-2,Gravity.TOP);tp.setMargins(dp(10),dp(9),dp(10),0);f.addView(top,tp);LinearLayout bot=row();bot.setGravity(Gravity.CENTER_VERTICAL);bot.setPadding(dp(11),dp(7),dp(11),dp(7));bot.setBackground(round(Color.argb(225,5,13,18),14,Color.rgb(52,66,70)));bot.addView(txt("GRĖSMĖ  ● žema   ● vidutinė   ● aukšta   ● labai aukšta",8,Color.rgb(193,205,206),true),new LinearLayout.LayoutParams(0,-2,1));Button center=small("CENTRUOTI");center.setOnClickListener(v->{world.resetView();haptic();});bot.addView(center);FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);bp.setMargins(dp(10),0,dp(10),dp(10));f.addView(bot,bp);return f;}

    @Override View journal(){ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(10),dp(6),dp(10),dp(20));sv.addView(c);FrameLayout h=new FrameLayout(this);h.addView(image(R.drawable.quest_meridian),new FrameLayout.LayoutParams(-1,dp(190)));View sh=new View(this);sh.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{Color.argb(20,0,0,0),Color.argb(240,3,9,13)}));h.addView(sh,new FrameLayout.LayoutParams(-1,dp(190)));LinearLayout q=col();q.setPadding(dp(15),0,dp(15),dp(13));q.addView(section("PAGRINDINĖ SIUŽETO LINIJA · I DALIS"));q.addView(serif("LŪŽĘS MERIDIANAS",24,PARCH,true));q.addView(txt("Atviri horizontai · vartų poslinkis · Orisono signalai",9,SUB,false));h.addView(q,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));c.addView(h,new LinearLayout.LayoutParams(-1,dp(190)));
        LinearLayout prog=surface(true);prog.addView(section("TIKSLAI"));prog.addView(step(true,false,"Manifestas pasiekė Luminara prieš karavaną"));prog.addView(step(false,true,state.objective));prog.addView(step(false,false,"Užsitikrinti tris nepriklausomai prižiūrimus kelio atramos taškus"));prog.addView(step(false,false,"Pereiti Meridianą ir grįžti su patikrinamais Orisono kontakto duomenimis"));prog.addView(step(false,false,"Derėtis dėl Pirmosios Meridiano chartijos arba ją atmesti"));c.addView(prog,sp(dp(9)));
        LinearLayout th=surface(false);th.addView(section("AKTYVIOS GIJOS"));for(String s:new String[]{"Kelionės vartų poslinkis","Orisono ryšio protokolas","Santarvės priežiūros valdymas","Drakoniškoji įpėdinystė"}){TextView x=txt(s,10,Color.rgb(211,218,213),true);x.setPadding(dp(10),dp(8),dp(10),dp(8));x.setBackground(round(Color.rgb(15,27,34),11,Color.rgb(40,58,66)));th.addView(x,sp(dp(5)));}c.addView(th,sp(dp(9)));FactionStatusView fs=new FactionStatusView(this);c.addView(fs,new LinearLayout.LayoutParams(-1,dp(165)));
        LinearLayout log=surface(false);log.addView(section("PASKUTINIAI ĖJIMAI"));if(state.recentTurns.isEmpty())log.addView(txt("Naujų vietinių ėjimų dar nėra.",10,SUB,false));else for(int i=state.recentTurns.size()-1;i>=0;i--)log.addView(txt("• "+state.recentTurns.get(i),10,Color.rgb(216,221,216),false),sp(dp(4)));c.addView(log,sp(dp(9)));return sv;}

    @Override View settings(){ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(10),dp(6),dp(10),dp(20));sv.addView(c);LinearLayout ai=surface(true);ai.addView(section("DI ŽAIDIMO MEISTRAS"));boolean has=!SecureKeyStore.load(this).isEmpty();ai.addView(txt(has?"Groq raktas saugomas Android raktų saugykloje":"Groq raktas nenustatytas",12,has?TEAL2:SUB,true));Button key=gold(has?"PAKEISTI API RAKTĄ":"ĮVESTI API RAKTĄ");key.setOnClickListener(v->key());ai.addView(key,sp(dp(6)));c.addView(ai,sp(dp(9)));LinearLayout vis=surface(false);vis.addView(section("PATEIKIMAS"));vis.addView(toggle("Sklandūs ekranų perėjimai","animations",true));vis.addView(toggle("Haptinis grįžtamasis ryšys","haptics",true));vis.addView(toggle("Subtilūs UI garsai","sounds",false));c.addView(vis,sp(dp(9)));LinearLayout sav=surface(false);sav.addView(section("IŠSAUGOJIMAS"));Button undo=dark("ATŠAUKTI PASKUTINĮ ĖJIMĄ");undo.setOnClickListener(v->{if(db.undo()){state=db.loadState();feedback="Atkurtas ankstesnis kontrolinis taškas";show("game");}else Toast.makeText(this,"Nėra ankstesnio kontrolinio taško",Toast.LENGTH_SHORT).show();});sav.addView(undo,sp(dp(5)));Button ex=dark("EKSPORTUOTI IŠSAUGOJIMĄ");ex.setOnClickListener(v->export());sav.addView(ex,sp(dp(5)));Button im=dark("IMPORTUOTI IŠSAUGOJIMĄ");im.setOnClickListener(v->importSave());sav.addView(im,sp(dp(5)));c.addView(sav,sp(dp(9)));LinearLayout about=surface(false);about.addView(section("APIE VERSIJĄ"));about.addView(serif("Vaeloria OOC · "+BuildConfig.VERSION_NAME,17,PARCH,true));about.addView(txt("Vietinė SQLite būsena · saugus Groq raktas · žemėlapis veikia be ryšio",10,SUB,false));about.addView(txt("Atsarginės sistemos kopijos išjungtos · ryšys tik per HTTPS",9,TEAL2,true));c.addView(about);return sv;}

    @Override void locationDialog(String name,int danger){boolean discovered=db.world().isDiscovered(name);LinearLayout box=col();box.setPadding(dp(18),dp(12),dp(18),dp(6));box.addView(serif(discovered?name:"Neatrasta kryptis",23,PARCH,true));box.addView(txt("GRĖSMĖ "+danger+"/10"+(discovered?" · "+faction(name):" · FRAKCIJA NEŽINOMA"),9,dangerColor(danger),true),sp(dp(8)));box.addView(txt(discovered?lore(name):"Atlasas rodo tik apytikrę kryptį. Pirmiausia reikia surinkti kelio žymes, gandus arba atlikti saugų žvalgymą.",12,Color.rgb(218,223,218),false),sp(dp(8)));int minutes=db.world().travelMinutes(state.location,name);if(discovered&&minutes>0)box.addView(txt("NUMATOMAS KELIONĖS LAIKAS · "+minutes+" pasaulio min.",9,GOLD2,true),sp(dp(6)));new AlertDialog.Builder(this).setView(box).setNegativeButton("UŽDARYTI",null).setPositiveButton(discovered?"KELIAUTI":"TIRTI KRYPTĮ",(d,w)->{show("game");act(discovered?"Keliauti iš "+state.location+" į "+name+" saugiausiu pagrįstu maršrutu, įvertinant laiką ir realias pasekmes.":"Saugiai tirti neatrastą kryptį link "+name+", rinkti kelio žymes ir nekeliauti aklai.");}).show();}
    @Override void act(String action){haptic();sound(true);super.act(action);} @Override public void onBackPressed(){if(!"game".equals(screen)){show("game");return;}super.onBackPressed();} @Override public void onDestroy(){if(audio!=null)audio.close();if(tone!=null)tone.release();super.onDestroy();}

    View resources(){LinearLayout s=row();s.setPadding(dp(4),dp(8),dp(4),dp(8));s.setBackground(round(Color.rgb(8,18,24),13,Color.rgb(35,52,60)));s.addView(res2("GYVYBĖ",state.hp,state.hpMax,Color.rgb(105,184,127)),w());s.addView(res2("MANA",state.mana,state.manaMax,Color.rgb(77,156,210)),w());s.addView(res2("IŠTVERMĖ",state.stamina,state.staminaMax,GOLD2),w());s.addView(res2("EONAS",state.aeonic,state.aeonicMax,Color.rgb(156,116,212)),w());return s;} LinearLayout.LayoutParams w(){return new LinearLayout.LayoutParams(0,-2,1);} View res2(String n,int v,int m,int col){LinearLayout x=col();x.setPadding(dp(4),0,dp(4),0);TextView a=txt(n,7,SUB,true);a.setGravity(Gravity.CENTER);x.addView(a);TextView b=txt(v+"/"+m,10,PARCH,true);b.setGravity(Gravity.CENTER);x.addView(b);ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(Math.max(1,m));p.setProgress(Math.max(0,v));p.setProgressTintList(ColorStateList.valueOf(col));p.setProgressBackgroundTintList(ColorStateList.valueOf(Color.rgb(27,39,45)));x.addView(p,new LinearLayout.LayoutParams(-1,dp(5)));return x;}
    View choice(int i,String a){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(10),dp(10),dp(10),dp(10));r.setBackground(round(Color.rgb(12,24,31),14,Color.rgb(42,60,68)));TextView n=serif(String.valueOf(i),16,GOLD2,true);n.setGravity(Gravity.CENTER);n.setBackground(round(Color.rgb(23,34,38),30,Color.argb(170,221,187,104)));r.addView(n,new LinearLayout.LayoutParams(dp(38),dp(38)));TextView t=txt(a,12,Color.rgb(231,233,226),false);t.setPadding(dp(10),0,0,0);r.addView(t,new LinearLayout.LayoutParams(0,-2,1));r.setOnClickListener(v->act(a));return r;}
    LinearLayout surface(boolean gold){LinearLayout x=col();x.setPadding(dp(13),dp(12),dp(13),dp(12));x.setBackground(round(gold?Color.rgb(13,25,32):Color.rgb(10,20,27),16,gold?Color.argb(140,221,187,104):Color.rgb(37,55,63)));return x;}TextView section(String s){TextView x=txt(s,9,GOLD2,true);x.setLetterSpacing(.08f);x.setPadding(0,0,0,dp(7));return x;}TextView txt(String s,int z,int c,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(accessibleTextSize(z));x.setTextColor(c);x.setTypeface(Typeface.create(Typeface.SANS_SERIF,b?Typeface.BOLD:Typeface.NORMAL));x.setLineSpacing(0,1.08f);return x;}TextView serif(String s,int z,int c,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(Math.max(10,accessibleTextSize(z)));x.setTextColor(c);x.setTypeface(Typeface.create(Typeface.SERIF,b?Typeface.BOLD:Typeface.NORMAL));x.setLineSpacing(0,1.06f);return x;}int accessibleTextSize(int requested){int value=Math.max(9,requested);return pref("large_text",false)?value+2:value;}ImageView image(int r){ImageView i=new ImageView(this);i.setImageResource(r);i.setScaleType(ImageView.ScaleType.CENTER_CROP);return i;}LinearLayout.LayoutParams sp(int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,b);return p;}
    View itemTile(VaeloriaDb.Item it){LinearLayout x=col();x.setPadding(dp(3),dp(3),dp(3),dp(3));ItemIconView icon=new ItemIconView(this);icon.setItem(it.name,it.slot,it.rarity);x.addView(icon,new LinearLayout.LayoutParams(-1,dp(88)));x.setOnClickListener(v->itemDialog(it));return x;}void itemDialog(VaeloriaDb.Item it){LinearLayout b=col();b.setPadding(dp(18),dp(14),dp(18),dp(6));b.addView(serif(it.name,21,PARCH,true));b.addView(txt(rarityLabel(it.rarity).toUpperCase(Locale.ROOT),9,rarity(it.rarity),true),sp(dp(7)));b.addView(txt(it.description,11,Color.rgb(218,223,218),false));new AlertDialog.Builder(this).setView(b).setPositiveButton("UŽDARYTI",null).show();}
    View step(boolean done,boolean active,String s){LinearLayout r=row();r.setPadding(0,dp(5),0,dp(5));r.addView(txt(done?"✓":active?"◆":"○",12,done?Color.rgb(105,184,127):active?GOLD2:Color.rgb(102,122,128),true),new LinearLayout.LayoutParams(dp(28),-2));r.addView(txt(s,10,active?PARCH:SUB,active),new LinearLayout.LayoutParams(0,-2,1));return r;}
    Switch toggle(String l,String k,boolean d){Switch s=new Switch(this);s.setText(l);s.setTextSize(accessibleTextSize(11));s.setTextColor(PARCH);s.setMinHeight(dp(48));s.setChecked(pref(k,d));s.setOnCheckedChangeListener((b,v)->getSharedPreferences("vaeloria_visual",MODE_PRIVATE).edit().putBoolean(k,v).apply());return s;}Button gold(String s){Button b=new Button(this);b.setText(s);b.setTextSize(accessibleTextSize(10));b.setTextColor(INK);b.setTypeface(Typeface.DEFAULT_BOLD);b.setMinHeight(dp(48));b.setBackground(round(GOLD2,12,GOLD2));return b;}Button outline(String s){Button b=new Button(this);b.setText(s);b.setTextSize(accessibleTextSize(10));b.setTextColor(GOLD2);b.setMinHeight(dp(48));b.setBackground(round(Color.rgb(8,18,24),12,Color.argb(180,221,187,104)));return b;}Button dark(String s){Button b=new Button(this);b.setText(s);b.setTextSize(accessibleTextSize(10));b.setTextColor(PARCH);b.setMinHeight(dp(48));b.setBackground(round(Color.rgb(11,23,30),12,Color.rgb(48,67,75)));return b;}Button small(String s){Button b=new Button(this);b.setText(s);b.setTextSize(accessibleTextSize(8));b.setTextColor(GOLD2);b.setMinHeight(dp(44));b.setBackground(round(Color.rgb(15,26,31),10,Color.argb(160,221,187,104)));return b;}
    boolean pref(String k,boolean d){return getSharedPreferences("vaeloria_visual",MODE_PRIVATE).getBoolean(k,d);}void haptic(){if(pref("haptics",true)&&root!=null)root.performHapticFeedback(Build.VERSION.SDK_INT>=30?HapticFeedbackConstants.CONFIRM:HapticFeedbackConstants.KEYBOARD_TAP);}void sound(boolean action){if(audio!=null){audio.cue(action?VaeloriaAudio.Cue.ACTION:VaeloriaAudio.Cue.NAVIGATE);return;}if(!pref("sounds",false))return;if(tone==null)tone=new ToneGenerator(AudioManager.STREAM_MUSIC,18);tone.startTone(action?ToneGenerator.TONE_PROP_ACK:ToneGenerator.TONE_PROP_BEEP,45);}int dangerColor(int d){if(pref("colorblind",false))return d>=8?Color.rgb(215,82,150):d>=6?Color.rgb(226,137,45):d>=4?Color.rgb(76,145,210):Color.rgb(79,178,151);return d>=8?Color.rgb(225,93,77):d>=6?Color.rgb(231,144,77):d>=4?GOLD2:Color.rgb(99,187,137);}String faction(String l){String s=l.toLowerCase(Locale.ROOT);return s.contains("kharad")||s.contains("drakono")||s.contains("pelen")?"DRAVENN":s.contains("safyro")||s.contains("slėn")||s.contains("pelkyn")||s.contains("labir")?"LYSARA":"ASTERRA";}
    void locationHub(){ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(14),dp(12),dp(14),dp(10));sv.addView(c);ImageView art=image(R.drawable.scene_luminara);c.addView(art,new LinearLayout.LayoutParams(-1,dp(130)));c.addView(serif("LUMINARA",22,PARCH,true),sp(dp(2)));c.addView(txt("Asterros sostinė · Meridiano vartų mazgas",9,SUB,false),sp(dp(9)));c.addView(section("ŽINOMOS VIETOS"));for(String place:new String[]{"Meridiano vartai","Didžioji akademija","Žibinto poilsio užeiga","Centrinė rinka","Rezonanso dirbtuvės"}){Button b=dark(place);b.setOnClickListener(v->act("Vykti į "+place+" Luminara mieste ir ištirti situaciją."));c.addView(b,sp(dp(4)));}c.addView(section("ŽMONĖS"),sp(dp(3)));for(String[] n:NPCS)c.addView(npcCard(n),sp(dp(5)));new AlertDialog.Builder(this).setView(sv).setNegativeButton("UŽDARYTI",null).show();}
    View npcCard(String[] n){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(9),dp(7),dp(9),dp(7));r.setBackground(round(Color.rgb(11,22,29),12,Color.rgb(40,57,65)));NpcPortraitV070 i=new NpcPortraitV070(this);i.setNpc(n[0],n[1]);r.addView(i,new LinearLayout.LayoutParams(dp(58),dp(68)));LinearLayout t=col();t.setPadding(dp(10),0,0,0);t.addView(serif(n[0],15,PARCH,true));t.addView(txt(n[1],9,SUB,false));r.addView(t,new LinearLayout.LayoutParams(0,-2,1));r.setOnClickListener(v->npcDialog(n));return r;}void npcDialog(String[] n){LinearLayout c=col();c.setPadding(dp(16),dp(12),dp(16),dp(8));NpcPortraitV070 portrait=new NpcPortraitV070(this);portrait.setNpc(n[0],n[1]);c.addView(portrait,new LinearLayout.LayoutParams(-1,dp(220)));c.addView(serif(n[0],22,PARCH,true),sp(dp(3)));c.addView(txt(n[1].toUpperCase(Locale.ROOT),8,GOLD2,true),sp(dp(8)));c.addView(txt(n[2],11,Color.rgb(217,222,217),false));new AlertDialog.Builder(this).setView(c).setNegativeButton("UŽDARYTI",null).setPositiveButton("KLAUSTI APIE MERIDIANĄ",(d,w)->act("Pasikalbėti su "+n[0]+" apie Lūžusį Meridianą ir išgirsti tik tai, ką šis žmogus realiai žino.")).show();}
}
