package lt.vaeloria.ooc;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;

public class VaeloriaActivity extends Activity {
    static final int BG=Color.rgb(7,15,22),SUR=Color.rgb(16,28,37),SUR2=Color.rgb(23,38,49),TEXT=Color.rgb(238,239,232),MUT=Color.rgb(166,183,188),GOLD=Color.rgb(214,182,107),TEAL=Color.rgb(82,177,167),GREEN=Color.rgb(94,185,131);
    VaeloriaDb db; GameState state; FrameLayout content; LinearLayout nav; String screen="game",feedback=""; boolean busy=false; final ExecutorService pool=Executors.newSingleThreadExecutor();

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);db=new VaeloriaDb(this);state=db.loadState();shell();show("game");}
    @Override public void onDestroy(){pool.shutdownNow();super.onDestroy();}

    void shell(){LinearLayout root=col();root.setBackgroundColor(BG);LinearLayout top=row();top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(18),dp(8),dp(14),dp(6));top.addView(t("VAELORIA",21,GOLD,true),new LinearLayout.LayoutParams(0,dp(50),1));top.addView(chip("LOCAL RPG · v0.2"));root.addView(top,new LinearLayout.LayoutParams(-1,dp(64)));content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav=row();nav.setPadding(dp(5),dp(5),dp(5),dp(8));nav.setBackgroundColor(Color.rgb(9,19,27));root.addView(nav,new LinearLayout.LayoutParams(-1,dp(70)));setContentView(root);}
    void nav(){nav.removeAllViews();tab("game","✦","ŽAISTI");tab("hero","♜","VEIKĖJAS");tab("map","⌖","ŽEMĖLAPIS");tab("journal","≡","ŽURNALAS");tab("settings","⚙","NUSTAT.");}
    void tab(String id,String icon,String label){LinearLayout x=col();x.setGravity(Gravity.CENTER);boolean a=id.equals(screen);x.setBackground(round(a?SUR2:Color.TRANSPARENT,15,a?Color.argb(90,214,182,107):Color.TRANSPARENT));TextView i=t(icon,19,a?GOLD:MUT,true);i.setGravity(Gravity.CENTER);x.addView(i);TextView l=t(label,9,a?TEXT:MUT,true);l.setGravity(Gravity.CENTER);x.addView(l);x.setOnClickListener(v->show(id));nav.addView(x,new LinearLayout.LayoutParams(0,-1,1));}
    void show(String id){screen=id;nav();content.removeAllViews();content.addView("game".equals(id)?game():"hero".equals(id)?hero():"map".equals(id)?map():"journal".equals(id)?journal():settings());}

    View game(){ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(14),dp(6),dp(14),dp(22));sv.addView(c);LinearLayout h=card();h.addView(t("📍 "+state.location+"  ·  METAI "+state.worldYear,15,TEXT,true));h.addView(t(clock(),11,MUT,false));c.addView(h,m(dp(8)));LinearLayout bars=row();bars.addView(res("HP",state.hp,state.hpMax,GREEN),w1());bars.addView(res("MANA",state.mana,state.manaMax,TEAL),w1());bars.addView(res("STAM",state.stamina,state.staminaMax,GOLD),w1());bars.addView(res("AEON",state.aeonic,state.aeonicMax,Color.rgb(154,115,212)),w1());c.addView(bars,m(dp(8)));if(!feedback.isEmpty()){TextView f=t(feedback,11,TEXT,true);f.setPadding(dp(10),dp(8),dp(10),dp(8));f.setBackground(round(Color.rgb(24,52,50),13,Color.argb(100,82,177,167)));c.addView(f,m(dp(9)));}
        if(state.combatActive){LinearLayout x=strong();x.addView(label("⚔ COMBAT · "+safe(state.enemyName,"PRIEŠAS").toUpperCase(Locale.ROOT)));CombatBoardView b=new CombatBoardView(this);b.setState(state);x.addView(b,new LinearLayout.LayoutParams(-1,dp(190)));x.addView(t("TELEGRAPH · "+safe(state.enemyTelegraph,"Neaiškus ketinimas"),12,Color.rgb(236,157,111),true));if(!state.enemyStatus.isEmpty())x.addView(t("Būsena: "+state.enemyStatus,11,MUT,false));c.addView(x,m(dp(10)));}else{SceneBannerView art=new SceneBannerView(this);art.setLocation(state.location);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(155));p.setMargins(0,0,0,dp(10));c.addView(art,p);}
        LinearLayout q=card();q.addView(label("AKTYVUS SIUŽETAS"));q.addView(t(state.questTitle,17,GOLD,true));q.addView(t(state.objective,12,MUT,false));c.addView(q,m(dp(10)));LinearLayout sc=strong();sc.addView(label("DABARTINĖ SCENA"));sc.addView(t(state.sceneTitle,21,TEXT,true));TextView story=t(state.scene,15,Color.rgb(225,229,225),false);story.setLineSpacing(0,1.15f);story.setPadding(0,dp(6),0,0);sc.addView(story);c.addView(sc,m(dp(11)));c.addView(label("KĄ DARAI?"));for(int i=0;i<Math.min(3,state.choices.size());i++){String a=state.choices.get(i);Button b=choice((i+1)+"  "+a);b.setEnabled(!busy);b.setOnClickListener(v->act(a));c.addView(b,m(dp(7)));}LinearLayout free=card();free.addView(label("LAISVAS VEIKSMAS"));EditText in=new EditText(this);in.setHint("Aprašyk bet kokį veiksmą…");in.setHintTextColor(Color.rgb(113,137,145));in.setTextColor(TEXT);in.setMinLines(2);in.setMaxLines(5);in.setBackground(round(Color.rgb(10,21,29),12,Color.rgb(43,65,76)));in.setPadding(dp(11),dp(8),dp(11),dp(8));free.addView(in);Button send=accent(busy?"SPRENDŽIAMA…":"ATLIKTI VEIKSMĄ");send.setEnabled(!busy);send.setOnClickListener(v->{String a=in.getText().toString().trim();if(!a.isEmpty())act(a);});free.addView(send,m(dp(6)));free.addView(t(SecureKeyStore.load(this).isEmpty()?"AI GM išjungtas · veikia lokalus fallback":"AI GM · Groq · gpt-oss-120b",10,SecureKeyStore.load(this).isEmpty()?MUT:TEAL,false));c.addView(free,m(dp(8)));return sv;}

    View hero(){ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(14),dp(6),dp(14),dp(22));sv.addView(c);LinearLayout top=strong();top.setGravity(Gravity.CENTER_HORIZONTAL);TextView e=t("E",35,BG,true);e.setGravity(Gravity.CENTER);e.setBackground(round(GOLD,45,GOLD));top.addView(e,new LinearLayout.LayoutParams(dp(82),dp(82)));TextView n=t("EINORAS",24,TEXT,true);n.setGravity(Gravity.CENTER);n.setPadding(0,dp(8),0,0);top.addView(n);top.addView(center("201 m. chronologinis · 20 m. biologinis · AGELESS",11,MUT));c.addView(top,m(dp(10)));LinearLayout stats=card();stats.addView(label("PROGRESIJA"));stats.addView(t("92 / 92 bazinės statistikos · 100/100",16,TEXT,true));stats.addView(bar("LEGENDARY CAP",100,100,GOLD));stats.addView(t("Tolesnė pažanga yra kokybinė post-cap mastery, ne papildomi bazinių statų taškai.",11,MUT,false));c.addView(stats,m(dp(9)));LinearLayout gear=card();gear.addView(label("EQUIPMENT"));for(VaeloriaDb.Item i:db.getItems())if(i.slot!=null)gear.addView(item(i));gear.addView(t("Weapon / armor / utility: po 1 · relic: iki 4. Aktyvus gear perduodamas GM kaip situacinės galimybės.",10,MUT,false));c.addView(gear,m(dp(9)));LinearLayout inv=card();inv.addView(label("ARTEFAKTAI"));for(VaeloriaDb.Item i:db.getItems())if(i.slot==null){inv.addView(t(i.name+" · "+i.rarity.toUpperCase(Locale.ROOT),13,rarity(i.rarity),true));inv.addView(t(i.description,10,MUT,false));}c.addView(inv,m(dp(9)));LinearLayout ab=card();ab.addView(label("POST-CAP GEBĖJIMAI"));for(String[] a:db.getAbilities())ab.addView(t("• "+a[0]+"  ·  "+a[1].replace('_',' '),11,TEXT,false));c.addView(ab,m(dp(8)));return sv;}
    View item(VaeloriaDb.Item i){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(6),0,dp(6));LinearLayout x=col();x.addView(t(slot(i.slot)+" · "+i.rarity.toUpperCase(Locale.ROOT),9,rarity(i.rarity),true));x.addView(t(i.name+(i.synced?"  ◈":""),14,TEXT,true));x.addView(t(i.description,10,MUT,false));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));Button b=small(i.equipped?"NUIMTI":"UŽSIDĖTI");b.setOnClickListener(v->{db.checkpoint("equipment",state);if(!db.toggleEquip(i.id))Toast.makeText(this,"Pasiektas relic limitas arba item neturi sloto",Toast.LENGTH_SHORT).show();feedback="⚙ Equipment: "+i.name;show("hero");});r.addView(b,new LinearLayout.LayoutParams(dp(95),dp(40)));return r;}

    View map(){LinearLayout root=col();root.setPadding(dp(10),dp(4),dp(10),dp(10));LinearLayout h=card();h.addView(label("PASAULIO ŽEMĖLAPIS"));h.addView(t("◆ "+state.location+" · pinch / drag / tap. Lokacija nekeičiama be realiai išspręstos kelionės.",11,MUT,false));root.addView(h,m(dp(7)));WorldMapView m=new WorldMapView(this);m.setCurrentLocation(state.location);m.setListener((name,danger)->new AlertDialog.Builder(this).setTitle(name+" · Pavojus "+danger+"/10").setMessage(lore(name)+"\n\nKelionė gali turėti laiką, kainą, encounter ar Waygate komplikaciją.").setNegativeButton("Uždaryti",null).setPositiveButton("KELIAUTI",(d,w)->{show("game");act("Keliauti iš "+state.location+" į "+name+" saugiausiu pagrįstu maršrutu; neišmesk kelionės pasekmių.");}).show());root.addView(m,new LinearLayout.LayoutParams(-1,0,1));return root;}

    View journal(){ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(14),dp(6),dp(14),dp(22));sv.addView(c);LinearLayout q=strong();q.addView(label("MAIN ARC · ACT I"));q.addView(t("THE BROKEN MERIDIAN",20,GOLD,true));q.addView(obj("◆",state.objective,true));q.addView(obj("○","Secure three independently maintained route anchors",false));q.addView(obj("○","Cross the Meridian and return with verifiable Orison contact data",false));q.addView(obj("○","Negotiate or reject the First Meridian Charter",false));c.addView(q,m(dp(9)));LinearLayout th=card();th.addView(label("AKTYVŪS THREADS"));for(String s:new String[]{"Open Horizons: The Broken Meridian · P96 · H58 · M82","Orison Contact Protocol · P90 · H55 · M85","Waygate Drift · P82 · H50 · M78","Concordance Stewardship Governance · P76 · H62 · M38","Draconic Succession · P74 · H46 · M52"})th.addView(t("• "+s,11,TEXT,false));c.addView(th,m(dp(9)));LinearLayout log=card();log.addView(label("PASKUTINIAI ĖJIMAI"));if(state.recentTurns.isEmpty())log.addView(t("Naujų lokalių ėjimų dar nėra.",11,MUT,false));else for(int i=state.recentTurns.size()-1;i>=0;i--)log.addView(t("• "+state.recentTurns.get(i),11,TEXT,false));c.addView(log,m(dp(8)));return sv;}

    View settings(){ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(14),dp(6),dp(14),dp(22));sv.addView(c);LinearLayout ai=strong();ai.addView(label("AI GAME MASTER"));boolean has=!SecureKeyStore.load(this).isEmpty();ai.addView(t(has?"Groq raktas saugomas Android Keystore":"Groq raktas nenustatytas",14,has?TEAL:MUT,true));Button key=accent(has?"PAKEISTI API RAKTĄ":"ĮVESTI API RAKTĄ");key.setOnClickListener(v->key());ai.addView(key,m(dp(5)));c.addView(ai,m(dp(9)));LinearLayout sav=card();sav.addView(label("SAVE / RECOVERY"));Button undo=outline("↶ ATŠAUKTI PASKUTINĮ ŽINGSNĮ");undo.setOnClickListener(v->{if(db.undo()){state=db.loadState();feedback="↶ Atkurtas checkpointas";show("game");}else Toast.makeText(this,"Nėra checkpointo",Toast.LENGTH_SHORT).show();});sav.addView(undo,m(dp(5)));Button ex=outline("KOPIJUOTI SAVE");ex.setOnClickListener(v->export());sav.addView(ex,m(dp(5)));Button im=outline("IMPORTUOTI SAVE");im.setOnClickListener(v->importSave());sav.addView(im,m(dp(5)));Button reset=outline("ATKURTI NEON CHECKPOINTĄ");reset.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Atkurti pradžią?").setMessage("Lokalūs ėjimai ir gear pakeitimai bus panaikinti; API raktas liks.").setNegativeButton("Ne",null).setPositiveButton("Atkurti",(d,w)->{db.reset();state=db.loadState();feedback="Atkurta Luminara kanoninė pradžia";show("game");}).show());sav.addView(reset);c.addView(sav,m(dp(9)));LinearLayout tech=card();tech.addView(label("ARCHITEKTŪRA"));tech.addView(t("Telefonas → SQLite → Groq tik scenos sprendimui",13,TEXT,true));tech.addView(t("Jokio Vercel ar nuolatinio backend. Be Groq rakto UI, map, gear, save ir lokalus fallback veikia toliau.",11,MUT,false));c.addView(tech,m(dp(8)));return sv;}

    void act(String action){if(busy)return;db.checkpoint("prieš veiksmą",state);busy=true;feedback="⟳ Sprendžiama…";show("game");String key=SecureKeyStore.load(this);pool.execute(()->{JSONObject r;String warn=null;try{r=key.isEmpty()?local(action):GroqClient.resolveTurn(key,state,action,db.equippedSummary(),db.getAbilities());}catch(Exception e){r=local(action);warn="Groq nepasiekiamas · lokalus fallback";}JSONObject rr=r;String ww=warn;runOnUiThread(()->finish(action,rr,ww));});}
    void finish(String action,JSONObject r,String warn){int hp=state.hp,ma=state.mana,st=state.stamina,ae=state.aeonic;long cr=state.crowns;String old=state.location;String event=r.optString("event_tag","none");state.applyTurn(r);state.recentTurns.add(action+" → "+state.sceneTitle);while(state.recentTurns.size()>12)state.recentTurns.remove(0);db.saveState(state);StringBuilder f=new StringBuilder();if(!"none".equals(event))f.append("◆ ").append(event.toUpperCase(Locale.ROOT)).append("  ");delta(f,"HP",state.hp-hp);delta(f,"Mana",state.mana-ma);delta(f,"Stamina",state.stamina-st);delta(f,"Aeonic",state.aeonic-ae);if(state.crowns!=cr)delta(f,"crowns",state.crowns-cr);if(!old.equals(state.location))f.append(" → ").append(state.location);if(f.length()==0)f.append("Veiksmas išspręstas · save atnaujintas");if(warn!=null)f.append("\n⚠ ").append(warn);feedback=f.toString();busy=false;show("game");}
    JSONObject local(String action){try{JSONObject r=new JSONObject();r.put("location",state.location).put("time_minutes",15).put("hp_delta",0).put("mana_delta",0).put("stamina_delta",0).put("aeonic_delta",0).put("crowns_delta",0).put("quest_note",state.objective).put("event_tag","discovery").put("combat_active",false).put("enemy_name","").put("enemy_status","").put("enemy_telegraph","").put("combat_distance","mid").put("combat_hazard","");JSONArray c=new JSONArray();String a=action.toLowerCase(Locale.ROOT);if(a.contains("manifest")||a.contains("ištir")||a.contains("tirti")){r.put("scene_title","Manifesto neatitikimas").put("scene","Datos ir antspaudai rodo dvi skirtingas, bet viduje nuoseklias laiko versijas. Tai neįrodo priežasties, tačiau vakarinio waygate tranzito žyma tampa pirmu patikrinamu pėdsaku.").put("quest_note","Patikrinti vakarinio Luminara waygate tranzito žymą ir palyginti ją su fizine karavano būsena.");c.put("Vykti prie vakarinio waygate").put("Surasti manifestą išdavusį raštininką").put("Palyginti plombas su Meridian Key rezonansu");}else if(a.contains("mira")||a.contains("kaelis")){r.put("scene_title","Trijų meistrų palyginimas").put("scene","Mira ir Kaelis mato ne vien laiko poslinkį, o galimą maršruto pasirinkimo neatitikimą. Jie siūlo du nepriklausomus matavimus prieš priimant teoriją.");c.put("Atlikti dvigubą matavimą").put("Paprašyti atskirų hipotezių").put("Paimti seną Meridian žemėlapį");}else if(a.contains("keliauti")||a.contains("vykti")||a.contains("waygate")){r.put("scene_title","Kelias į incidento vietą").put("scene","Kelionė prasideda stabiliai, bet artėjant prie waygate tranzito ritmas ima skirtis. Sargyba riboja civilių prieigą, todėl tolesnis žingsnis turi ir praktinę, ir politinę kainą.").put("event_tag","travel").put("time_minutes",35);c.put("Prašyti ribotos oficialios prieigos").put("Stebėti zoną iš išorės").put("Ieškoti teisėto alternatyvaus maršruto");}else{r.put("scene_title","Veiksmo pasekmė").put("scene","Veiksmas keičia situaciją, bet neapeina nežinomų Meridian taisyklių. Patikimiausia toliau remtis patikrinamais įrodymais.");c.put("Rinkti fizinius įrodymus").put("Kalbėtis su liudininkais atskirai").put("Patikrinti Meridian Key reakciją");}return r.put("choices",c);}catch(Exception e){return new JSONObject();}}

    void key(){EditText i=new EditText(this);i.setHint("gsk_…");i.setSingleLine(true);i.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle("Groq API raktas").setMessage("Šifruojamas Android Keystore ir lieka šiame telefone.").setView(i).setNegativeButton("Atšaukti",null).setPositiveButton("Išsaugoti",(d,w)->{try{String k=i.getText().toString().trim();if(k.length()<10)throw new Exception();SecureKeyStore.save(this,k);show("settings");}catch(Exception e){Toast.makeText(this,"Nepavyko išsaugoti rakto",Toast.LENGTH_SHORT).show();}}).show();}
    void export(){((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Vaeloria save",db.exportSave()));Toast.makeText(this,"Save nukopijuotas",Toast.LENGTH_SHORT).show();}
    void importSave(){ClipboardManager cm=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(!cm.hasPrimaryClip()){Toast.makeText(this,"Iškarpinė tuščia",Toast.LENGTH_SHORT).show();return;}String x=cm.getPrimaryClip().getItemAt(0).coerceToText(this).toString();if(db.importSave(x)){state=db.loadState();feedback="Save importuotas";show("game");}else Toast.makeText(this,"Netinkamas Vaeloria save",Toast.LENGTH_SHORT).show();}

    LinearLayout card(){LinearLayout x=col();x.setPadding(dp(13),dp(12),dp(13),dp(12));x.setBackground(round(SUR,17,Color.rgb(36,57,68)));return x;} LinearLayout strong(){LinearLayout x=col();x.setPadding(dp(14),dp(13),dp(14),dp(13));x.setBackground(round(SUR2,19,Color.argb(130,214,182,107)));return x;} LinearLayout col(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);return x;} LinearLayout row(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.HORIZONTAL);return x;}
    TextView t(String s,int z,int color,boolean bold){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(color);x.setTypeface(Typeface.create(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL));x.setLineSpacing(0,1.08f);return x;} TextView label(String s){TextView x=t(s,10,GOLD,true);x.setPadding(0,0,0,dp(6));return x;} TextView center(String s,int z,int color){TextView x=t(s,z,color,false);x.setGravity(Gravity.CENTER);return x;} TextView chip(String s){TextView x=t(s,9,TEAL,true);x.setGravity(Gravity.CENTER);x.setPadding(dp(9),0,dp(9),0);x.setBackground(round(Color.argb(55,82,177,167),18,Color.argb(90,82,177,167)));return x;}
    Button choice(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(12);b.setTextColor(TEXT);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setBackground(round(SUR2,15,Color.rgb(47,70,81)));return b;} Button accent(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(BG);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(GOLD,13,GOLD));return b;} Button outline(String s){Button b=new Button(this);b.setText(s);b.setTextSize(10);b.setTextColor(TEXT);b.setBackground(round(Color.TRANSPARENT,13,Color.rgb(55,80,91)));return b;} Button small(String s){Button b=new Button(this);b.setText(s);b.setTextSize(9);b.setTextColor(TEXT);b.setBackground(round(Color.argb(40,255,255,255),11,Color.rgb(75,103,113)));return b;}
    LinearLayout res(String name,int v,int max,int color){LinearLayout x=col();x.setPadding(dp(2),0,dp(2),0);TextView a=center(name,9,MUT);x.addView(a);TextView n=center(v+"/"+max,12,TEXT);n.setTypeface(Typeface.DEFAULT_BOLD);x.addView(n);ProgressBar b=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);b.setMax(max);b.setProgress(v);b.setProgressTintList(android.content.res.ColorStateList.valueOf(color));b.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(34,49,57)));x.addView(b,new LinearLayout.LayoutParams(-1,dp(6)));return x;} View bar(String name,int v,int max,int color){LinearLayout x=col();x.addView(t(name+"  "+v+"/"+max,10,MUT,true));ProgressBar b=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);b.setMax(max);b.setProgress(v);b.setProgressTintList(android.content.res.ColorStateList.valueOf(color));x.addView(b,new LinearLayout.LayoutParams(-1,dp(7)));return x;} View obj(String icon,String s,boolean a){LinearLayout x=row();x.setPadding(0,dp(6),0,dp(6));x.addView(t(icon,14,a?GOLD:MUT,true),new LinearLayout.LayoutParams(dp(26),-2));x.addView(t(s,11,a?TEXT:MUT,a),new LinearLayout.LayoutParams(0,-2,1));return x;}
    GradientDrawable round(int fill,int r,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));if(Color.alpha(stroke)>0)g.setStroke(dp(1),stroke);return g;} LinearLayout.LayoutParams m(int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,bottom);return p;} LinearLayout.LayoutParams w1(){return new LinearLayout.LayoutParams(0,dp(55),1);} int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} int rarity(String r){return "unique".equals(r)?Color.rgb(229,118,210):"legendary".equals(r)?GOLD:"ancient".equals(r)?Color.rgb(188,115,224):"rare".equals(r)?Color.rgb(88,157,225):TEXT;} String slot(String s){return "primary_weapon".equals(s)?"WEAPON":"armor_system".equals(s)?"ARMOR":"utility".equals(s)?"UTILITY":"relic".equals(s)?"RELIC":"ITEM";} String safe(String s,String d){return s==null||s.isEmpty()?d:s;} String clock(){long day=state.worldMinute/1440,mn=state.worldMinute%1440;return "Diena "+day+" · "+String.format(Locale.ROOT,"%02d:%02d",mn/60,mn%60);} String lore(String n){if("Luminara".equals(n))return "Septynių plaukiojančių maginių žiedų metropolis.";if(n.contains("Dragonwake"))return "Drakonų teritorija ir aukšto pavojingumo kalnai.";if(n.contains("Kharad"))return "Forge-city ir null-resistant amato centras.";if(n.contains("Hollow"))return "Erdvinės ir null anomalijos persidengia.";return "Kanoninė Vaeloria lokacija, susieta su gyvu travel network.";} void delta(StringBuilder b,String n,long d){if(d!=0){if(b.length()>0)b.append("  ");b.append(d>0?"+":"").append(d).append(" ").append(n);}}
}
