plugins {
    id 'com.android.application'
}

android {
    namespace 'lt.vaeloria.ooc'
    compileSdk 35

    defaultConfig {
        applicationId 'lt.vaeloria.ooc.personal'
        minSdk 26
        targetSdk 35
        versionCode 33
        versionName '0.9.3'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildFeatures {
        buildConfig = true
    }

    signingConfigs {
        vaeloriaStable {
            storeFile file("${System.getProperty('user.home')}/.android/debug.keystore")
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    buildTypes {
        debug {
            debuggable false
            signingConfig signingConfigs.vaeloriaStable
        }
        release {
            debuggable false
            minifyEnabled false
            signingConfig signingConfigs.vaeloriaStable
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
    androidTestImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
