package lt.vaeloria.ooc;

import android.content.Context;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import java.util.*;

class WorldMapView extends View {
    interface Listener { void onLocationSelected(String name,int danger); }
    static class N { String name; float x,y; int danger; N(String n,float x,float y,int d){name=n;this.x=x;this.y=y;danger=d;} }
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG); final Bitmap map; final ArrayList<N> ns=new ArrayList<>(); final ScaleGestureDetector scaleDetector; final GestureDetector gestures;
    Listener listener; String current="Luminara",selected=""; float base=1,zoom=1,tx,ty,lastX,lastY; boolean drag;
    WorldMapView(Context c){ super(c); setBackgroundColor(Color.rgb(3,9,14)); map=BitmapFactory.decodeResource(getResources(),R.drawable.world_map_v060);
        add("Luminara",388,405,3);add("Asterio Karūna",270,183,4);add("Stiklo Giria",505,180,5);add("Veyrhold",620,326,3);add("Aureliono Pakraštys",705,513,4);add("Žvaigždėkritos Skliautas",525,512,7);add("Tuščiavidurė Smailė",110,613,8);add("Pelenų Karūnos Citadelė",925,275,7);add("Kharad Vorn",1180,365,5);add("Drakono Pabudimo Viršūnės",1175,90,8);add("Safyro Platybės",967,600,7);add("Amžinojo Šaltinio Slėnis",770,741,4);add("Šventųjų Pelkynas",617,920,6);add("Žaliasis Labirintas",1190,790,8);
        scaleDetector=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){float before=base*zoom,mx=(d.getFocusX()-tx)/before,my=(d.getFocusY()-ty)/before;zoom=Math.max(1,Math.min(4.5f,zoom*d.getScaleFactor()));float after=base*zoom;tx=d.getFocusX()-mx*after;ty=d.getFocusY()-my*after;clamp();invalidate();return true;}});
        gestures=new GestureDetector(c,new GestureDetector.SimpleOnGestureListener(){public boolean onDoubleTap(MotionEvent e){if(zoom>1.1f)resetView();else zoomAt(e.getX(),e.getY(),2.2f);return true;}});
    }
    void add(String n,float x,float y,int d){ns.add(new N(n,x,y,d));} void setListener(Listener l){listener=l;} void setCurrentLocation(String s){current=s==null?"Luminara":s;invalidate();} String getSelected(){return selected;}
    N find(String s){if(s==null)return null;for(N n:ns)if(n.name.equalsIgnoreCase(s)||aliases(n.name,s))return n;return null;} boolean aliases(String a,String b){return(a.startsWith("Asterio")&&b.contains("Crown"))||(a.startsWith("Stiklo")&&b.contains("Glasswood"))||(a.startsWith("Aureliono")&&b.contains("Aurelion"))||(a.startsWith("Žvaigždė")&&b.contains("Starfall"))||(a.startsWith("Tuščiavidurė")&&b.contains("Hollow"))||(a.startsWith("Pelenų")&&b.contains("Ashen"))||(a.startsWith("Drakono")&&b.contains("Dragonwake"))||(a.startsWith("Safyro")&&b.contains("Sapphire"))||(a.startsWith("Amžinojo")&&b.contains("Everspring"))||(a.startsWith("Šventųjų")&&b.contains("Mire"))||(a.startsWith("Žaliasis")&&b.contains("Verdant"));}
    protected void onSizeChanged(int w,int h,int ow,int oh){resetView();} void resetView(){if(map==null||getWidth()==0||getHeight()==0)return;base=Math.max(getWidth()/(float)map.getWidth(),getHeight()/(float)map.getHeight());zoom=1;N n=find(current);float s=base;tx=getWidth()/2f-(n==null?map.getWidth()/2f:n.x)*s;ty=getHeight()/2f-(n==null?map.getHeight()/2f:n.y)*s;clamp();invalidate();}
    protected void onDraw(Canvas c){super.onDraw(c);if(map==null)return;float s=base*zoom;c.save();c.translate(tx,ty);c.scale(s,s);c.drawBitmap(map,0,0,p);N here=find(current);long tm=System.currentTimeMillis()%1500;float pulse=tm/1500f;if(here!=null){float inv=1/s;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3*inv);p.setColor(Color.argb((int)(190*(1-pulse)),245,205,102));c.drawCircle(here.x,here.y,(18+25*pulse)*inv,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(245,205,102));c.drawCircle(here.x,here.y,8*inv,p);}N sel=find(selected);if(sel!=null){float inv=1/s;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3*inv);p.setColor(Color.rgb(92,190,178));c.drawCircle(sel.x,sel.y,18*inv,p);p.setStyle(Paint.Style.FILL);}c.restore();if(isAttachedToWindow())postInvalidateDelayed(40);}
    public boolean onTouchEvent(MotionEvent e){gestures.onTouchEvent(e);scaleDetector.onTouchEvent(e);switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:getParent().requestDisallowInterceptTouchEvent(true);lastX=e.getX();lastY=e.getY();drag=false;return true;case MotionEvent.ACTION_MOVE:if(!scaleDetector.isInProgress()){float dx=e.getX()-lastX,dy=e.getY()-lastY;if(Math.abs(dx)+Math.abs(dy)>5)drag=true;tx+=dx;ty+=dy;lastX=e.getX();lastY=e.getY();clamp();invalidate();}return true;case MotionEvent.ACTION_UP:if(!drag)select(e.getX(),e.getY());getParent().requestDisallowInterceptTouchEvent(false);return true;case MotionEvent.ACTION_CANCEL:getParent().requestDisallowInterceptTouchEvent(false);return true;}return true;}
    void select(float sx,float sy){float s=base*zoom,mx=(sx-tx)/s,my=(sy-ty)/s;N best=null;float bd=Float.MAX_VALUE;for(N n:ns){float dx=n.x-mx,dy=n.y-my,d=dx*dx+dy*dy;if(d<bd){bd=d;best=n;}}if(best!=null&&bd<70*70){selected=best.name;performClick();invalidate();if(listener!=null)listener.onLocationSelected(best.name,best.danger);}} public boolean performClick(){super.performClick();return true;}
    void zoomAt(float x,float y,float z){float before=base*zoom,mx=(x-tx)/before,my=(y-ty)/before;zoom=z;float after=base*zoom;tx=x-mx*after;ty=y-my*after;clamp();invalidate();} void clamp(){if(map==null)return;float sw=map.getWidth()*base*zoom,sh=map.getHeight()*base*zoom,m=dp(55);tx=sw<=getWidth()?(getWidth()-sw)/2:Math.max(getWidth()-sw-m,Math.min(m,tx));ty=sh<=getHeight()?(getHeight()-sh)/2:Math.max(getHeight()-sh-m,Math.min(m,ty));} int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

class SceneBannerView extends View {
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG); final Bitmap city,wild,map; String location="Luminara",scene="",event=""; long minute;
    SceneBannerView(Context c){super(c);city=BitmapFactory.decodeResource(getResources(),R.drawable.scene_luminara);wild=BitmapFactory.decodeResource(getResources(),R.drawable.combat_forest);map=BitmapFactory.decodeResource(getResources(),R.drawable.world_map_v060);}
    void setLocation(String l){setScene(l,"","",0);} void setScene(String l,String s,String e,long m){location=l==null?"Luminara":l;scene=s==null?"":s;event=e==null?"":e;minute=m;invalidate();}
    protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();String q=(location+" "+scene).toLowerCase(Locale.ROOT);Bitmap b=q.contains("luminara")?city:(q.contains("giria")||q.contains("pelkyn")||q.contains("labir"))?wild:map;cover(c,b,w,h);p.setShader(new LinearGradient(0,0,0,h,Color.argb(10,0,0,0),Color.argb(230,2,7,10),Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);p.setTypeface(Typeface.create(Typeface.SERIF,Typeface.BOLD));p.setTextSize(dp(24));p.setColor(Color.rgb(244,226,185));c.drawText(location.toUpperCase(Locale.forLanguageTag("lt-LT")),dp(16),h-dp(42),p);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(10));p.setColor(Color.rgb(191,204,204));c.drawText(trim(scene,46),dp(17),h-dp(20),p);}
    void cover(Canvas c,Bitmap b,int w,int h){if(b==null)return;float s=Math.max(w/(float)b.getWidth(),h/(float)b.getHeight());int sw=Math.round(w/s),sh=Math.round(h/s),l=Math.max(0,(b.getWidth()-sw)/2),t=Math.max(0,(b.getHeight()-sh)/2);c.drawBitmap(b,new Rect(l,t,Math.min(b.getWidth(),l+sw),Math.min(b.getHeight(),t+sh)),new RectF(0,0,w,h),p);}String trim(String s,int n){return s==null?"":s.length()>n?s.substring(0,n-1)+"…":s;}int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

class CombatBoardView extends View {
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);final Bitmap bg;GameState state;CombatBoardView(Context c){super(c);bg=BitmapFactory.decodeResource(getResources(),R.drawable.combat_forest);}void setState(GameState s){state=s;invalidate();}
    protected void onDraw(Canvas c){if(state==null)return;int w=getWidth(),h=getHeight();cover(c,bg,w,h);p.setShader(new LinearGradient(0,0,0,h,Color.argb(70,0,0,0),Color.argb(235,2,7,10),Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);label(c,dp(14),dp(22),"EINORAS",Color.rgb(221,187,104));String en=state.enemyName==null||state.enemyName.isEmpty()?"PRIEŠAS":state.enemyName;labelRight(c,w-dp(14),dp(22),en.toUpperCase(Locale.ROOT),Color.rgb(221,91,77));String dist="close".equals(state.combatDistance)?"ARTIMAS":"far".equals(state.combatDistance)?"TOLIMAS":"VIDUTINIS";p.setTextSize(dp(9));p.setTypeface(Typeface.DEFAULT_BOLD);p.setColor(Color.rgb(208,216,214));float tw=p.measureText(dist);c.drawText(dist,w/2f-tw/2,dp(25),p);RectF box=new RectF(dp(12),h-dp(90),w-dp(12),h-dp(10));p.setColor(Color.argb(225,5,13,18));c.drawRoundRect(box,dp(12),dp(12),p);p.setColor(Color.rgb(232,150,91));p.setTextSize(dp(8));p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("PRIEŠO KETINIMAS",box.left+dp(10),box.top+dp(17),p);p.setTextSize(dp(11));p.setColor(Color.rgb(236,238,231));p.setTypeface(Typeface.DEFAULT);String tel=state.enemyTelegraph==null||state.enemyTelegraph.isEmpty()?"Ketinimas dar neaiškus":state.enemyTelegraph;c.drawText(trim(tel,54),box.left+dp(10),box.top+dp(39),p);p.setTextSize(dp(8));p.setColor(Color.rgb(182,198,194));String st=state.enemyStatus==null||state.enemyStatus.isEmpty()?"Būsena nežinoma":state.enemyStatus;c.drawText("BŪSENA · "+trim(st,42),box.left+dp(10),box.top+dp(58),p);String hz=state.combatHazard==null||state.combatHazard.isEmpty()?"Aplinka stabili":state.combatHazard;p.setColor(Color.rgb(221,187,104));c.drawText("APLINKA · "+trim(hz,42),box.left+dp(10),box.top+dp(75),p);}
    void label(Canvas c,float x,float y,String s,int col){p.setTypeface(Typeface.create(Typeface.SERIF,Typeface.BOLD));p.setTextSize(dp(12));p.setColor(col);c.drawText(s,x,y,p);}void labelRight(Canvas c,float x,float y,String s,int col){p.setTypeface(Typeface.create(Typeface.SERIF,Typeface.BOLD));p.setTextSize(dp(12));p.setColor(col);c.drawText(s,x-p.measureText(s),y,p);}void cover(Canvas c,Bitmap b,int w,int h){if(b==null)return;float s=Math.max(w/(float)b.getWidth(),h/(float)b.getHeight());int sw=Math.round(w/s),sh=Math.round(h/s),l=Math.max(0,(b.getWidth()-sw)/2),t=Math.max(0,(b.getHeight()-sh)/2);c.drawBitmap(b,new Rect(l,t,Math.min(b.getWidth(),l+sw),Math.min(b.getHeight(),t+sh)),new RectF(0,0,w,h),p);}String trim(String s,int n){return s.length()>n?s.substring(0,n-1)+"…":s;}int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

class CharacterLoadoutView extends View {
    interface Listener{void onSlotPressed(String slot);}static class S{String title,item;int col;S(String t,String i,int c){title=t;item=i;col=c;}}final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);final Bitmap hero;final LinkedHashMap<String,S> slots=new LinkedHashMap<>();final LinkedHashMap<String,RectF> hits=new LinkedHashMap<>();Listener listener;
    CharacterLoadoutView(Context c){super(c);hero=BitmapFactory.decodeResource(getResources(),R.drawable.hero_einoras);}void setListener(Listener l){listener=l;}void put(String k,String t,String i,int c){slots.put(k,new S(t,i,c));invalidate();}
    protected void onDraw(Canvas c){hits.clear();int w=getWidth(),h=getHeight();p.setColor(Color.rgb(6,13,18));c.drawRoundRect(0,0,w,h,dp(18),dp(18),p);if(hero!=null)c.drawBitmap(hero,null,new RectF(w*.22f,dp(20),w*.78f,h-dp(68)),p);String[] ks={"head","neck","weapon","offhand","chest","utility","hands","belt","legs","feet","ring_left","ring_right"};float bw=Math.min(dp(125),w*.31f),bh=dp(46),y=dp(32);for(int i=0;i<ks.length;i+=2){slot(c,ks[i],dp(8),y,bw,bh);slot(c,ks[i+1],w-bw-dp(8),y,bw,bh);y+=dp(54);}String[] rs={"relic_1","relic_2","relic_3","relic_4"};float gap=dp(5),rw=(w-dp(18)-gap*3)/4f,ry=h-dp(56);for(int i=0;i<4;i++)slot(c,rs[i],dp(9)+i*(rw+gap),ry,rw,dp(46));}
    void slot(Canvas c,String k,float x,float y,float w,float h){S s=slots.get(k);boolean eq=s!=null&&s.item!=null&&!s.item.isEmpty();int col=eq?s.col:Color.rgb(62,78,85);RectF r=new RectF(x,y,x+w,y+h);hits.put(k,r);p.setColor(Color.argb(215,7,17,23));c.drawRoundRect(r,dp(10),dp(10),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(col);c.drawRoundRect(r,dp(10),dp(10),p);p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(7));p.setColor(col);String title=s==null?k:s.title;c.drawText(fit(title.toUpperCase(Locale.ROOT),w-dp(12)),x+dp(6),y+dp(15),p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(dp(8));p.setColor(eq?Color.rgb(236,236,229):Color.rgb(116,133,138));c.drawText(fit(eq?s.item:"Tuščia",w-dp(12)),x+dp(6),y+dp(34),p);}
    String fit(String s,float m){if(p.measureText(s)<=m)return s;String x=s;while(x.length()>2&&p.measureText(x+"…")>m)x=x.substring(0,x.length()-1);return x+"…";}public boolean onTouchEvent(MotionEvent e){if(e.getActionMasked()==MotionEvent.ACTION_UP)for(Map.Entry<String,RectF> q:hits.entrySet())if(q.getValue().contains(e.getX(),e.getY())){performClick();if(listener!=null)listener.onSlotPressed(q.getKey());return true;}return true;}public boolean performClick(){super.performClick();return true;}int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

class NavGlyphView extends View {final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);String kind;boolean active;NavGlyphView(Context c,String k){super(c);kind=k;}void setActive(boolean a){active=a;invalidate();}protected void onDraw(Canvas c){float x=getWidth()/2f,y=getHeight()/2f;p.setColor(active?Color.rgb(221,187,104):Color.rgb(145,163,168));p.setStrokeWidth(dp(2));p.setStyle(Paint.Style.STROKE);p.setStrokeCap(Paint.Cap.ROUND);if("hero".equals(kind)){c.drawCircle(x,y-dp(5),dp(4),p);c.drawArc(x-dp(9),y,x+dp(9),y+dp(16),195,150,false,p);}else if("map".equals(kind)){c.drawCircle(x,y,dp(9),p);c.drawLine(x-dp(12),y,x+dp(12),y,p);c.drawLine(x,y-dp(12),x,y+dp(12),p);c.drawCircle(x,y,dp(2),p);}else if("journal".equals(kind)){c.drawRect(x-dp(8),y-dp(10),x+dp(8),y+dp(10),p);for(int i=-1;i<=1;i++)c.drawLine(x-dp(4),y+i*dp(5),x+dp(4),y+i*dp(5),p);}else if("settings".equals(kind)){c.drawCircle(x,y,dp(7),p);for(int i=0;i<8;i++){double a=i*Math.PI/4;c.drawLine((float)(x+Math.cos(a)*dp(9)),(float)(y+Math.sin(a)*dp(9)),(float)(x+Math.cos(a)*dp(12)),(float)(y+Math.sin(a)*dp(12)),p);}}else{c.drawLine(x,y-dp(10),x,y+dp(10),p);c.drawLine(x-dp(10),y,x+dp(10),y,p);c.drawLine(x-dp(7),y-dp(7),x+dp(7),y+dp(7),p);c.drawLine(x+dp(7),y-dp(7),x-dp(7),y+dp(7),p);}p.setStyle(Paint.Style.FILL);}int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}}

class ItemIconView extends View {final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);String name="",rarity="common";int accent=Color.rgb(120,140,148);ItemIconView(Context c){super(c);}void setItem(String n,String cat,String r){name=n==null?"":n;rarity=r==null?"common":r;accent=rarityColor(rarity);invalidate();}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();RectF r=new RectF(dp(2),dp(2),w-dp(2),h-dp(2));p.setColor(Color.rgb(9,19,26));c.drawRoundRect(r,dp(12),dp(12),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(2));p.setColor(accent);c.drawRoundRect(r,dp(12),dp(12),p);float x=w/2f,y=h*.42f;c.drawCircle(x,y,dp(14),p);c.drawLine(x-dp(10),y+dp(10),x+dp(10),y-dp(10),p);p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(7));p.setColor(Color.rgb(226,229,222));String s=name.length()>13?name.substring(0,12)+"…":name;float tw=p.measureText(s);c.drawText(s,(w-tw)/2,h-dp(7),p);}int rarityColor(String r){if("unique".equals(r))return Color.rgb(222,113,205);if("legendary".equals(r))return Color.rgb(223,185,90);if("ancient".equals(r))return Color.rgb(149,113,216);if("rare".equals(r))return Color.rgb(79,158,221);if("uncommon".equals(r))return Color.rgb(92,187,126);return Color.rgb(126,144,151);}int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}}

class FactionStatusView extends View {final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);FactionStatusView(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setColor(Color.rgb(9,19,26));c.drawRoundRect(0,0,w,h,dp(16),dp(16),p);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(9));p.setColor(Color.rgb(221,187,104));c.drawText("PASAULIO ĮTAMPA · MERIDIANO KRIZĖ",dp(13),dp(23),p);float y=dp(39);p.setColor(Color.rgb(28,40,46));c.drawRoundRect(dp(13),y,w-dp(13),y+dp(8),dp(4),dp(4),p);p.setColor(Color.rgb(211,160,76));c.drawRoundRect(dp(13),y,dp(13)+(w-dp(26))*.58f,y+dp(8),dp(4),dp(4),p);String[] n={"ASTERRA","DRAVENN","LYSARA"},s={"NEUTRALI","ĮTAMPA","SĄJUNGINĖ"};int[] col={Color.rgb(111,156,198),Color.rgb(206,101,69),Color.rgb(120,174,99)};for(int i=0;i<3;i++){float x=w*(i+.5f)/3f;p.setColor(Color.argb(80,Color.red(col[i]),Color.green(col[i]),Color.blue(col[i])));c.drawCircle(x,dp(95),dp(24),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(2));p.setColor(col[i]);c.drawCircle(x,dp(95),dp(24),p);p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.create(Typeface.SERIF,Typeface.BOLD));p.setTextSize(dp(9));p.setColor(Color.rgb(235,223,193));float tw=p.measureText(n[i]);c.drawText(n[i],x-tw/2,dp(132),p);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(7));p.setColor(col[i]);tw=p.measureText(s[i]);c.drawText(s[i],x-tw/2,dp(148),p);}}int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}}
