from pathlib import Path

p = Path('app/src/main/java/lt/vaeloria/ooc/VaeloriaActivity.java')
s = p.read_text(encoding='utf-8')

# Require a Groq-looking key without depending on exact validation generated by prior patches.
if 'k.startsWith("gsk_")' not in s:
    target = 'SecureKeyStore.save(this,k);'
    idx = s.find(target)
    if idx < 0:
        raise SystemExit('Could not locate Groq key save call')
    s = s[:idx] + 'if(!k.startsWith("gsk_")||k.length()<20)throw new Exception();' + s[idx:]

p.write_text(s, encoding='utf-8')

check = p.read_text(encoding='utf-8')
assert 'k.startsWith("gsk_")' in check
print('v0.5 reliability patch applied; offline stat engine preserved')
