package lt.vaeloria.ooc;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;

/** Vaeloria v0.7.0 — focused premium mobile presentation over the existing mechanics/database. */
public class PolishedActivity extends PremiumActivity {
    static final int V070_LINE=Color.rgb(43,59,68),V070_PANEL=Color.rgb(9,19,27),V070_PANEL2=Color.rgb(13,25,34),V070_BLUE=Color.rgb(91,164,207),V070_GREEN=Color.rgb(95,186,139),V070_PURPLE=Color.rgb(158,117,214);

    @Override void shell(){
        root=col();root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{Color.rgb(2,8,13),Color.rgb(5,14,21),Color.rgb(2,8,13)}));
        root.setOnApplyWindowInsetsListener((v,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars());top=bars.top;bottom=bars.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return insets;});
        LinearLayout top=row();top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(18),0,dp(8),0);top.setBackgroundColor(Color.rgb(3,10,16));
        LinearLayout brand=col();brand.addView(serif("VAELORIA",24,GOLD2,true));TextView version=txt("OOC · LOCAL FIRST · v0.7.0",7,Color.rgb(112,135,142),true);version.setLetterSpacing(.09f);brand.addView(version);top.addView(brand,new LinearLayout.LayoutParams(0,dp(62),1));
        LinearLayout loc=col();loc.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);TextView l=txt(state.location.toUpperCase(Locale.forLanguageTag("lt-LT")),8,PARCH,true);l.setGravity(Gravity.END);TextView y=txt("METAI "+state.worldYear,7,SUB,false);y.setGravity(Gravity.END);loc.addView(l);loc.addView(y);top.addView(loc,new LinearLayout.LayoutParams(dp(126),dp(62)));
        TextView gear=txt("⚙",21,PARCH,false);gear.setGravity(Gravity.CENTER);gear.setOnClickListener(v->{haptic();show("settings");});top.addView(gear,new LinearLayout.LayoutParams(dp(52),dp(58)));root.addView(top,new LinearLayout.LayoutParams(-1,dp(62)));
        View line=new View(this);line.setBackgroundColor(Color.rgb(26,40,49));root.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));
        content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav=row();nav.setPadding(dp(4),dp(3),dp(4),dp(5));nav.setBackgroundColor(Color.rgb(3,10,16));root.addView(nav,new LinearLayout.LayoutParams(-1,dp(74)));setContentView(root);root.requestApplyInsets();
    }

    @Override void nav(){nav.removeAllViews();tab070("game","✦","ŽAISTI");tab070("hero","♙","VEIKĖJAS");tab070("items","◇","DAIKTAI");tab070("map","⌖","ŽEMĖLAPIS");tab070("journal","◆","UŽDUOTYS");}
    void tab070(String id,String glyph,String label){LinearLayout x=col();x.setGravity(Gravity.CENTER);boolean a=id.equals(screen);if(a)x.setBackground(round(Color.rgb(18,30,38),15,Color.argb(150,221,187,104)));TextView g=txt(glyph,20,a?GOLD2:Color.rgb(118,139,146),true);g.setGravity(Gravity.CENTER);x.addView(g,new LinearLayout.LayoutParams(-1,dp(29)));TextView t=txt(label,8,a?PARCH:Color.rgb(132,150,156),true);t.setGravity(Gravity.CENTER);x.addView(t);x.setOnClickListener(v->{haptic();sound(false);show(id);});nav.addView(x,new LinearLayout.LayoutParams(0,-1,1));}

    @Override void show(String id){screen=id;nav();content.removeAllViews();View v;try{v="game".equals(id)?game():"hero".equals(id)?hero():"items".equals(id)?items():"map".equals(id)?map():"journal".equals(id)?journal():settings();}catch(Throwable e){v=errorView(e);}content.addView(v);if(pref("animations",true)){v.setAlpha(0);v.setTranslationY(dp(7));v.animate().alpha(1).translationY(0).setDuration(170).start();}}

    @Override View game(){
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);LinearLayout c=col();c.setPadding(dp(10),dp(7),dp(10),dp(18));sv.addView(c);
        if(state.combatActive){CombatBoardView b=new CombatBoardView(this);b.setState(state);c.addView(b,new LinearLayout.LayoutParams(-1,dp(300)));}else{SceneV070View art=new SceneV070View(this);art.setScene(state.location,state.sceneTitle);c.addView(art,new LinearLayout.LayoutParams(-1,dp(252)));}
        c.addView(resources(),sp(dp(8)));
        if(!feedback.isEmpty()){TextView f=txt(feedback,10,Color.rgb(216,230,223),true);f.setPadding(dp(11),dp(8),dp(11),dp(8));f.setBackground(round(Color.rgb(13,38,36),12,Color.argb(120,92,184,174)));c.addView(f,sp(dp(8)));}
        LinearLayout story=panel(true);story.addView(section070("DABARTINĖ SCENA"));story.addView(serif(state.sceneTitle,23,PARCH,true),sp(dp(6)));TextView body=txt(state.scene,14,Color.rgb(226,229,222),false);body.setLineSpacing(dp(2),1.10f);story.addView(body);c.addView(story,sp(dp(9)));
        LinearLayout quest=panel(false);LinearLayout qh=row();qh.setGravity(Gravity.CENTER_VERTICAL);qh.addView(section070("PAGRINDINĖ UŽDUOTIS"),new LinearLayout.LayoutParams(0,-2,1));qh.addView(chip070("AKTYVU",GOLD2));quest.addView(qh);quest.addView(serif(state.questTitle,16,PARCH,true));quest.addView(txt(state.objective,10,SUB,false));quest.setOnClickListener(v->show("journal"));c.addView(quest,sp(dp(10)));
        c.addView(section070("KĄ DARAI?"),sp(dp(5)));for(int i=0;i<Math.min(3,state.choices.size());i++){String a=state.choices.get(i);c.addView(choice070(i+1,a),sp(dp(6)));}
        if(!state.combatActive){Button explore=outline("TYRINĖTI "+state.location.toUpperCase(Locale.forLanguageTag("lt-LT")));explore.setOnClickListener(v->{haptic();locationHub();});c.addView(explore,sp(dp(9)));}
        LinearLayout free=panel(false);LinearLayout fh=row();fh.setGravity(Gravity.CENTER_VERTICAL);fh.addView(section070("LAISVAS VEIKSMAS"),new LinearLayout.LayoutParams(0,-2,1));boolean ai=!SecureKeyStore.load(this).isEmpty();fh.addView(chip070(ai?"AI GM":"LOCAL",ai?V070_GREEN:V070_BLUE));free.addView(fh);EditText in=new EditText(this);in.setHint("Aprašyk bet kokį veiksmą…");in.setHintTextColor(Color.rgb(102,124,132));in.setTextColor(Color.rgb(238,238,231));in.setTextSize(13);in.setMinLines(2);in.setMaxLines(4);in.setPadding(dp(11),dp(9),dp(11),dp(9));in.setBackground(round(Color.rgb(6,15,22),12,Color.rgb(42,60,70)));free.addView(in,sp(dp(7)));Button send=gold(busy?"SPRENDŽIAMA…":"ATLIKTI VEIKSMĄ  →");send.setEnabled(!busy);send.setOnClickListener(v->{String a=in.getText().toString().trim();if(!a.isEmpty())act(a);});free.addView(send);c.addView(free);return sv;
    }

    @Override View hero(){
        ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(10),dp(7),dp(10),dp(20));sv.addView(c);
        FrameLayout top=new FrameLayout(this);ImageView art=image(R.drawable.hero_einoras_v070);art.setScaleType(ImageView.ScaleType.CENTER_CROP);top.addView(art,new FrameLayout.LayoutParams(-1,dp(350)));View shade=new View(this);shade.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{Color.argb(8,0,0,0),Color.argb(240,2,8,13)}));top.addView(shade,new FrameLayout.LayoutParams(-1,dp(350)));LinearLayout ov=col();ov.setPadding(dp(16),0,dp(16),dp(15));ov.addView(section070("VEIKĖJAS"));ov.addView(serif("EINORAS",29,PARCH,true));ov.addView(txt("201 m. chronologinis  ·  20 m. biologinis  ·  amžius nekinta",9,SUB,false));LinearLayout tags=row();tags.setPadding(0,dp(7),0,0);tags.addView(chip070("92/92 · 100/100",GOLD2));tags.addView(chip070("POST-CAP",V070_PURPLE));ov.addView(tags);top.addView(ov,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));c.addView(top,new LinearLayout.LayoutParams(-1,dp(350)));c.addView(resources(),sp(dp(8)));
        LinearLayout mastery=panel(false);mastery.addView(section070("MEISTRIŠKUMAS"));mastery.addView(serif("Legendary bazė · kokybinis progresas",17,PARCH,true));mastery.addView(txt("Skaitinis cap pasiektas. Toliau augama per principus, technikas, nežinomų taisyklių kalibraciją ir lygiaverčių meistrų praktiką.",10,SUB,false));c.addView(mastery,sp(dp(9)));
        LoadoutV070View load=new LoadoutV070View(this);String[] slots={"head","neck","weapon","offhand","chest","utility","hands","belt","legs","feet","ring_left","ring_right","relic_1","relic_2","relic_3","relic_4"};for(String s:slots){VaeloriaDb.Item it=db.getEquippedAt(s);load.put(s,VaeloriaDb.slotLabel(s),it==null?"":it.name,it==null?"":it.rarity,it==null?Color.rgb(67,84,92):rarity(it.rarity));}load.setListener(this::openSlot);c.addView(load,new LinearLayout.LayoutParams(-1,dp(560)));
        TextView gearHint=txt("Bakstelėk equipment slotą, kad pakeistum įrangą. Inventorius perkeltas į atskirą „Daiktai“ ekraną.",9,SUB,false);gearHint.setPadding(dp(4),dp(7),dp(4),dp(9));c.addView(gearHint);
        LinearLayout ab=panel(false);LinearLayout ah=row();ah.setGravity(Gravity.CENTER_VERTICAL);ah.addView(section070("POST-CAP GEBĖJIMAI"),new LinearLayout.LayoutParams(0,-2,1));ah.addView(chip070(String.valueOf(db.getAbilities().size()),V070_PURPLE));ab.addView(ah);for(String[] a:db.getAbilities())ab.addView(abilityCard(a));c.addView(ab);return sv;
    }

    View items(){
        ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(10),dp(7),dp(10),dp(20));sv.addView(c);LinearLayout head=panel(true);head.addView(section070("INVENTORIUS"));head.addView(serif("Relikvijos ir įranga",23,PARCH,true));List<VaeloriaDb.Item> items=db.getItems();int eq=0,sync=0;for(VaeloriaDb.Item it:items){if(it.equipped)eq++;if(it.synced)sync++;}head.addView(txt(items.size()+" objektų  ·  "+eq+" aktyviai įrengti  ·  "+sync+" resonance synced",10,SUB,false));c.addView(head,sp(dp(9)));
        for(int i=0;i<items.size();i+=2){LinearLayout row=row();for(int j=0;j<2;j++){if(i+j<items.size()){VaeloriaDb.Item it=items.get(i+j);row.addView(itemCard070(it),new LinearLayout.LayoutParams(0,dp(186),1));}else row.addView(new View(this),new LinearLayout.LayoutParams(0,dp(186),1));}c.addView(row,sp(dp(7)));}
        return sv;
    }

    View itemCard070(VaeloriaDb.Item it){LinearLayout x=col();x.setPadding(dp(10),dp(10),dp(10),dp(9));int col=rarity(it.rarity);x.setBackground(round(V070_PANEL2,14,Color.argb(145,Color.red(col),Color.green(col),Color.blue(col))));ItemGlyphV070 icon=new ItemGlyphV070(this);icon.setItem(it.name,it.rarity);x.addView(icon,new LinearLayout.LayoutParams(-1,dp(92)));TextView n=serif(it.name,13,PARCH,true);n.setMaxLines(1);x.addView(n,sp(dp(2)));x.addView(txt(rarityLabel(it.rarity).toUpperCase(Locale.ROOT),8,col,true));String state=(it.equipped?"● ĮRENGTA":"○ INVENTORIUJE")+(it.synced?" · SYNC":"");x.addView(txt(state,7,it.synced?V070_GREEN:SUB,true));x.setOnClickListener(v->{haptic();itemDialog(it);});return x;}

    @Override View map(){
        FrameLayout f=new FrameLayout(this);WorldMapV070View world=new WorldMapV070View(this);world.setCurrentLocation(state.location);world.setListener(this::locationDialog);f.addView(world,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout top=panel(false);LinearLayout th=row();th.setGravity(Gravity.CENTER_VERTICAL);LinearLayout tt=col();tt.addView(section070("PASAULIO ATLASAS"));tt.addView(serif(state.location,18,PARCH,true));th.addView(tt,new LinearLayout.LayoutParams(0,-2,1));th.addView(chip070("◆ EINORAS",GOLD2));top.addView(th);top.addView(txt("Žnybk · tempk · dukart bakstelėk · paliesk lokaciją",8,SUB,false));FrameLayout.LayoutParams tp=new FrameLayout.LayoutParams(-1,-2,Gravity.TOP);tp.setMargins(dp(10),dp(9),dp(10),0);f.addView(top,tp);
        LinearLayout bot=row();bot.setGravity(Gravity.CENTER_VERTICAL);bot.setPadding(dp(11),dp(7),dp(11),dp(7));bot.setBackground(round(Color.argb(232,4,12,18),14,V070_LINE));bot.addView(txt("● žema   ● vidutinė   ● aukšta   ● labai aukšta",8,Color.rgb(193,205,206),true),new LinearLayout.LayoutParams(0,-2,1));Button center=small("CENTRUOTI");center.setOnClickListener(v->{world.resetView();haptic();});bot.addView(center);FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);bp.setMargins(dp(10),0,dp(10),dp(10));f.addView(bot,bp);return f;
    }

    @Override View journal(){
        ScrollView sv=new ScrollView(this);LinearLayout c=col();c.setPadding(dp(10),dp(7),dp(10),dp(20));sv.addView(c);FrameLayout h=new FrameLayout(this);h.addView(image(R.drawable.quest_meridian),new FrameLayout.LayoutParams(-1,dp(185)));View sh=new View(this);sh.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{Color.argb(18,0,0,0),Color.argb(245,2,8,13)}));h.addView(sh,new FrameLayout.LayoutParams(-1,dp(185)));LinearLayout q=col();q.setPadding(dp(15),0,dp(15),dp(13));q.addView(section070("PAGRINDINĖ SIUŽETO LINIJA · I DALIS"));q.addView(serif("LŪŽĘS MERIDIANAS",24,PARCH,true));q.addView(txt("Atviri horizontai · vartų poslinkis · Orisono signalai",9,SUB,false));h.addView(q,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));c.addView(h,new LinearLayout.LayoutParams(-1,dp(185)));
        LinearLayout prog=panel(true);prog.addView(section070("TIKSLAI"));prog.addView(step(true,false,"Manifestas pasiekė Luminara prieš karavaną"));prog.addView(step(false,true,state.objective));prog.addView(step(false,false,"Užsitikrinti tris nepriklausomai prižiūrimus kelio atramos taškus"));prog.addView(step(false,false,"Pereiti Meridianą ir grįžti su patikrinamais Orisono kontakto duomenimis"));prog.addView(step(false,false,"Derėtis dėl Pirmosios Meridiano chartijos arba ją atmesti"));c.addView(prog,sp(dp(9)));
        LinearLayout th=panel(false);th.addView(section070("AKTYVIOS PASAULIO GIJOS"));thread070(th,"Kelionės vartų poslinkis",82,50,78);thread070(th,"Orisono ryšio protokolas",90,55,85);thread070(th,"Santarvės priežiūros valdymas",76,62,38);thread070(th,"Drakoniškoji įpėdinystė",74,46,52);c.addView(th,sp(dp(9)));FactionStatusView fs=new FactionStatusView(this);c.addView(fs,new LinearLayout.LayoutParams(-1,dp(165)));
        LinearLayout log=panel(false);log.addView(section070("PASKUTINIAI ĖJIMAI"));if(state.recentTurns.isEmpty())log.addView(txt("Naujų vietinių ėjimų dar nėra.",10,SUB,false));else for(int i=state.recentTurns.size()-1;i>=0;i--)log.addView(txt("• "+state.recentTurns.get(i),10,Color.rgb(216,221,216),false),sp(dp(4)));c.addView(log);return sv;
    }

    LinearLayout panel(boolean gold){LinearLayout x=col();x.setPadding(dp(13),dp(12),dp(13),dp(12));x.setBackground(round(gold?Color.rgb(12,24,32):V070_PANEL,16,gold?Color.argb(150,221,187,104):V070_LINE));return x;}
    TextView section070(String s){TextView x=txt(s,9,GOLD2,true);x.setLetterSpacing(.09f);x.setPadding(0,0,0,dp(6));return x;}
    TextView chip070(String s,int color){TextView x=txt(s,8,color,true);x.setGravity(Gravity.CENTER);x.setPadding(dp(8),dp(4),dp(8),dp(4));x.setBackground(round(Color.argb(34,Color.red(color),Color.green(color),Color.blue(color)),18,Color.argb(110,Color.red(color),Color.green(color),Color.blue(color))));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(0,0,dp(5),dp(4));x.setLayoutParams(lp);return x;}
    View choice070(int i,String a){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(10),dp(10),dp(10),dp(10));r.setBackground(round(Color.rgb(11,23,31),14,Color.rgb(43,60,69)));TextView n=serif(String.valueOf(i),16,GOLD2,true);n.setGravity(Gravity.CENTER);n.setBackground(round(Color.rgb(23,34,38),30,Color.argb(180,221,187,104)));r.addView(n,new LinearLayout.LayoutParams(dp(38),dp(38)));TextView t=txt(a,12,Color.rgb(233,234,228),false);t.setPadding(dp(10),0,0,0);r.addView(t,new LinearLayout.LayoutParams(0,-2,1));TextView arrow=txt("›",22,Color.rgb(112,131,137),false);r.addView(arrow,new LinearLayout.LayoutParams(dp(24),-2));r.setOnClickListener(v->act(a));return r;}
    View abilityCard(String[] a){LinearLayout r=col();r.setPadding(dp(10),dp(9),dp(10),dp(9));r.setBackground(round(Color.rgb(12,24,32),12,Color.rgb(39,55,64)));LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);TextView name=serif(a[0],13,PARCH,true);h.addView(name,new LinearLayout.LayoutParams(0,-2,1));int col=abilityColor(a[1]);h.addView(chip070(abilityType(a[1]),col));r.addView(h);r.addView(txt(a[2],9,SUB,false));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(6));r.setLayoutParams(lp);return r;}
    int abilityColor(String type){String t=type.toLowerCase(Locale.ROOT);if(t.contains("ability"))return V070_GREEN;if(t.contains("refinement"))return V070_BLUE;if(t.contains("principle"))return V070_PURPLE;return GOLD2;}
    void thread070(LinearLayout parent,String title,int priority,int heat,int mystery){LinearLayout r=col();r.setPadding(dp(10),dp(8),dp(10),dp(8));r.setBackground(round(Color.rgb(11,23,30),11,Color.rgb(38,54,63)));LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);h.addView(txt(title,10,PARCH,true),new LinearLayout.LayoutParams(0,-2,1));h.addView(chip070("P"+priority,priority>=90?GOLD2:V070_BLUE));r.addView(h);r.addView(txt("Heat "+heat+"  ·  Mystery "+mystery,8,SUB,false));parent.addView(r,sp(dp(5)));}
}
