package lt.vaeloria.ooc;

import android.content.Context;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import java.util.*;

/** v0.7 premium visual layer. Pure Android Canvas; no runtime image/network dependency. */
class WorldMapV070View extends View {
    interface Listener { void onLocationSelected(String name,int danger); }
    static final class N { final String name; final float x,y; final int danger; N(String n,float x,float y,int d){name=n;this.x=x;this.y=y;danger=d;} }
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG); final Bitmap map; final ArrayList<N> ns=new ArrayList<>();
    final ScaleGestureDetector scaleDetector; final GestureDetector gestures; Listener listener; String current="Luminara", selected="";
    float base=1,zoom=1,tx,ty,lastX,lastY; boolean drag;
    WorldMapV070View(Context c){super(c);setBackgroundColor(Color.rgb(3,8,13));map=BitmapFactory.decodeResource(getResources(),R.drawable.world_map_v060);
        add("Luminara",388,405,3);add("Asterio Karūna",270,183,4);add("Stiklo Giria",505,180,5);add("Veyrhold",620,326,3);add("Aureliono Pakraštys",705,513,4);add("Žvaigždėkritos Skliautas",525,512,7);add("Tuščiavidurė Smailė",110,613,8);add("Pelenų Karūnos Citadelė",925,275,7);add("Kharad Vorn",1180,365,5);add("Drakono Pabudimo Viršūnės",1175,90,8);add("Safyro Platybės",967,600,7);add("Amžinojo Šaltinio Slėnis",770,741,4);add("Šventųjų Pelkynas",617,920,6);add("Žaliasis Labirintas",1190,790,8);
        scaleDetector=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){float before=base*zoom,mx=(d.getFocusX()-tx)/before,my=(d.getFocusY()-ty)/before;zoom=Math.max(1,Math.min(4.5f,zoom*d.getScaleFactor()));float after=base*zoom;tx=d.getFocusX()-mx*after;ty=d.getFocusY()-my*after;clamp();invalidate();return true;}});
        gestures=new GestureDetector(c,new GestureDetector.SimpleOnGestureListener(){public boolean onDoubleTap(MotionEvent e){if(zoom>1.1f)resetView();else zoomAt(e.getX(),e.getY(),2.25f);return true;}});
    }
    void add(String n,float x,float y,int d){ns.add(new N(n,x,y,d));} void setListener(Listener l){listener=l;} void setCurrentLocation(String s){current=s==null?"Luminara":s;invalidate();}
    N find(String s){if(s==null)return null;for(N n:ns)if(n.name.equalsIgnoreCase(s)||aliases(n.name,s))return n;return null;}
    boolean aliases(String a,String b){return(a.startsWith("Asterio")&&b.contains("Crown"))||(a.startsWith("Stiklo")&&b.contains("Glasswood"))||(a.startsWith("Aureliono")&&b.contains("Aurelion"))||(a.startsWith("Žvaigždė")&&b.contains("Starfall"))||(a.startsWith("Tuščiavidurė")&&b.contains("Hollow"))||(a.startsWith("Pelenų")&&b.contains("Ashen"))||(a.startsWith("Drakono")&&b.contains("Dragonwake"))||(a.startsWith("Safyro")&&b.contains("Sapphire"))||(a.startsWith("Amžinojo")&&b.contains("Everspring"))||(a.startsWith("Šventųjų")&&b.contains("Mire"))||(a.startsWith("Žaliasis")&&b.contains("Verdant"));}
    protected void onSizeChanged(int w,int h,int ow,int oh){resetView();} void resetView(){if(map==null||getWidth()==0||getHeight()==0)return;base=Math.max(getWidth()/(float)map.getWidth(),getHeight()/(float)map.getHeight());if(base<=0)base=1;zoom=1;N n=find(current);float s=base;tx=getWidth()/2f-(n==null?map.getWidth()/2f:n.x)*s;ty=getHeight()/2f-(n==null?map.getHeight()/2f:n.y)*s;clamp();invalidate();}
    protected void onDraw(Canvas c){super.onDraw(c);if(map==null)return;float s=base*zoom;c.save();c.translate(tx,ty);c.scale(s,s);c.drawBitmap(map,0,0,p);float inv=1/s;N here=find(current);if(here!=null){float pulse=(System.currentTimeMillis()%1700)/1700f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3.2f*inv);p.setColor(Color.argb((int)(190*(1-pulse)),242,202,105));c.drawCircle(here.x,here.y,(15+27*pulse)*inv,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(242,202,105));p.setShadowLayer(12*inv,0,0,p.getColor());c.drawCircle(here.x,here.y,7.5f*inv,p);p.clearShadowLayer();}N sel=find(selected);if(sel!=null){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3*inv);p.setColor(Color.rgb(91,191,183));c.drawCircle(sel.x,sel.y,17*inv,p);p.setStyle(Paint.Style.FILL);}c.restore();if(isAttachedToWindow())postInvalidateDelayed(60);}
    public boolean onTouchEvent(MotionEvent e){gestures.onTouchEvent(e);scaleDetector.onTouchEvent(e);switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:getParent().requestDisallowInterceptTouchEvent(true);lastX=e.getX();lastY=e.getY();drag=false;return true;case MotionEvent.ACTION_MOVE:if(!scaleDetector.isInProgress()){float dx=e.getX()-lastX,dy=e.getY()-lastY;if(Math.abs(dx)+Math.abs(dy)>6)drag=true;tx+=dx;ty+=dy;lastX=e.getX();lastY=e.getY();clamp();invalidate();}return true;case MotionEvent.ACTION_UP:if(!drag)select(e.getX(),e.getY());getParent().requestDisallowInterceptTouchEvent(false);return true;case MotionEvent.ACTION_CANCEL:getParent().requestDisallowInterceptTouchEvent(false);return true;}return true;}
    void select(float sx,float sy){float s=base*zoom,mx=(sx-tx)/s,my=(sy-ty)/s;N best=null;float bd=Float.MAX_VALUE;for(N n:ns){float dx=n.x-mx,dy=n.y-my,d=dx*dx+dy*dy;if(d<bd){bd=d;best=n;}}if(best!=null&&bd<70*70){selected=best.name;performClick();invalidate();if(listener!=null)listener.onLocationSelected(best.name,best.danger);}}
    public boolean performClick(){super.performClick();return true;}void zoomAt(float x,float y,float z){float before=base*zoom,mx=(x-tx)/before,my=(y-ty)/before;zoom=z;float after=base*zoom;tx=x-mx*after;ty=y-my*after;clamp();invalidate();}
    void clamp(){if(map==null)return;float sw=map.getWidth()*base*zoom,sh=map.getHeight()*base*zoom,m=dp(55);tx=sw<=getWidth()?(getWidth()-sw)/2:Math.max(getWidth()-sw-m,Math.min(m,tx));ty=sh<=getHeight()?(getHeight()-sh)/2:Math.max(getHeight()-sh-m,Math.min(m,ty));}int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

class SceneV070View extends View {
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG); final Bitmap luminara,wild,map; String location="Luminara", scene="";
    SceneV070View(Context c){super(c);setLayerType(LAYER_TYPE_SOFTWARE,null);luminara=BitmapFactory.decodeResource(getResources(),R.drawable.scene_luminara);wild=BitmapFactory.decodeResource(getResources(),R.drawable.combat_forest);map=BitmapFactory.decodeResource(getResources(),R.drawable.world_map_v060);}
    void setScene(String l,String s){location=l==null?"Luminara":l;scene=s==null?"":s;invalidate();}
    protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();String q=(location+" "+scene).toLowerCase(Locale.ROOT);Bitmap b=q.contains("luminara")?luminara:(q.contains("giria")||q.contains("pelkyn")||q.contains("labir")||q.contains("peak"))?wild:map;cover(c,b,w,h);p.setShader(new LinearGradient(0,0,0,h,new int[]{Color.argb(8,0,0,0),Color.argb(45,0,0,0),Color.argb(238,2,7,11)},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);
        p.setColor(Color.argb(165,3,9,14));c.drawRoundRect(new RectF(dp(12),dp(12),dp(128),dp(39)),dp(14),dp(14),p);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(8));p.setColor(Color.rgb(221,187,104));c.drawText("GYVA SCENA",dp(26),dp(30),p);
        p.setTypeface(Typeface.create(Typeface.SERIF,Typeface.BOLD));p.setTextSize(dp(25));p.setColor(Color.rgb(245,229,194));p.setShadowLayer(dp(5),0,2,Color.BLACK);c.drawText(location.toUpperCase(Locale.forLanguageTag("lt-LT")),dp(16),h-dp(45),p);p.clearShadowLayer();p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(10));p.setColor(Color.rgb(191,204,206));c.drawText(trim(scene,54),dp(17),h-dp(21),p);
    }
    void cover(Canvas c,Bitmap b,int w,int h){if(b==null)return;float s=Math.max(w/(float)b.getWidth(),h/(float)b.getHeight());int sw=Math.round(w/s),sh=Math.round(h/s),l=Math.max(0,(b.getWidth()-sw)/2),t=Math.max(0,(b.getHeight()-sh)/2);c.drawBitmap(b,new Rect(l,t,Math.min(b.getWidth(),l+sw),Math.min(b.getHeight(),t+sh)),new RectF(0,0,w,h),p);}String trim(String s,int n){return s==null?"":s.length()>n?s.substring(0,n-1)+"…":s;}int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

class ItemGlyphV070 extends View {
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);String name="",rarity="rare";int accent=Color.rgb(92,184,174);
    ItemGlyphV070(Context c){super(c);setLayerType(LAYER_TYPE_SOFTWARE,null);}void setItem(String n,String r){name=n==null?"":n;rarity=r==null?"rare":r;accent=color(rarity);invalidate();}
    int color(String r){return "unique".equals(r)?Color.rgb(220,125,215):"ancient".equals(r)?Color.rgb(135,133,232):"legendary".equals(r)?Color.rgb(221,187,104):Color.rgb(92,184,174);}
    protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),cx=w/2,cy=h/2;p.setShader(new RadialGradient(cx,cy,Math.max(w,h)*.55f,Color.argb(78,Color.red(accent),Color.green(accent),Color.blue(accent)),Color.argb(0,0,0,0),Shader.TileMode.CLAMP));c.drawCircle(cx,cy,Math.min(w,h)*.48f,p);p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(Color.argb(150,Color.red(accent),Color.green(accent),Color.blue(accent)));c.drawRoundRect(new RectF(1,1,w-1,h-1),dp(12),dp(12),p);p.setStrokeWidth(dp(2.5f));p.setStrokeCap(Paint.Cap.ROUND);p.setColor(accent);p.setShadowLayer(dp(5),0,0,Color.argb(120,Color.red(accent),Color.green(accent),Color.blue(accent)));drawGlyph(c,cx,cy,Math.min(w,h)*.27f);p.clearShadowLayer();p.setStyle(Paint.Style.FILL);}
    void drawGlyph(Canvas c,float x,float y,float r){String n=name.toLowerCase(Locale.ROOT);if(n.contains("edge")){c.drawLine(x-r*.7f,y+r,x+r*.65f,y-r,p);c.drawLine(x-r*.9f,y+r*.2f,x-r*.2f,y+r*.9f,p);}else if(n.contains("mantle")){Path q=new Path();q.moveTo(x,y-r);q.lineTo(x+r*.9f,y-r*.4f);q.lineTo(x+r*.65f,y+r*.7f);q.lineTo(x,y+r);q.lineTo(x-r*.65f,y+r*.7f);q.lineTo(x-r*.9f,y-r*.4f);q.close();c.drawPath(q,p);}else if(n.contains("prism")){Path q=new Path();q.moveTo(x,y-r);q.lineTo(x+r*.85f,y+r*.7f);q.lineTo(x-r*.85f,y+r*.7f);q.close();c.drawPath(q,p);c.drawLine(x,y-r,x,y+r*.7f,p);}else if(n.contains("key")){c.drawCircle(x-r*.35f,y-r*.25f,r*.38f,p);c.drawLine(x-r*.05f,y,x+r*.8f,y+r*.8f,p);c.drawLine(x+r*.48f,y+r*.48f,x+r*.75f,y+r*.17f,p);}else if(n.contains("compass")||n.contains("astrolabe")){c.drawCircle(x,y,r,p);c.drawCircle(x,y,r*.35f,p);c.drawLine(x,y-r*.78f,x+r*.35f,y+r*.55f,p);}else if(n.contains("heart")){Path q=new Path();q.moveTo(x,y+r*.8f);q.cubicTo(x-r*1.25f,y,x-r*.55f,y-r,x,y-r*.35f);q.cubicTo(x+r*.55f,y-r,x+r*1.25f,y,x,y+r*.8f);c.drawPath(q,p);}else if(n.contains("seed")){c.drawOval(new RectF(x-r*.4f,y-r,x+r*.4f,y+r),p);c.drawLine(x,y+r*.75f,x+r*.65f,y-r*.25f,p);}else if(n.contains("scale")){Path q=new Path();q.moveTo(x,y-r);q.quadTo(x+r*1.05f,y,x,y+r);q.quadTo(x-r*1.05f,y,x,y-r);c.drawPath(q,p);}else if(n.contains("seal")||n.contains("signet")){c.drawCircle(x,y,r,p);c.drawCircle(x,y,r*.4f,p);c.drawLine(x-r*.75f,y,x+r*.75f,y,p);c.drawLine(x,y-r*.75f,x,y+r*.75f,p);}else if(n.contains("satchel")){c.drawRoundRect(new RectF(x-r,y-r*.45f,x+r,y+r*.8f),r*.25f,r*.25f,p);c.drawArc(new RectF(x-r*.55f,y-r,x+r*.55f,y),180,180,false,p);}else{c.drawCircle(x,y,r,p);c.drawCircle(x,y,r*.35f,p);}}
    int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}

class LoadoutV070View extends View {
    interface Listener{void onSlotPressed(String slot);}static final class S{String title,item,rarity;int col;S(String t,String i,String r,int c){title=t;item=i;rarity=r;col=c;}}
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);final Bitmap hero;final LinkedHashMap<String,S> slots=new LinkedHashMap<>();final LinkedHashMap<String,RectF> hits=new LinkedHashMap<>();Listener listener;
    LoadoutV070View(Context c){super(c);setLayerType(LAYER_TYPE_SOFTWARE,null);hero=BitmapFactory.decodeResource(getResources(),R.drawable.hero_einoras);}void setListener(Listener l){listener=l;}void put(String k,String t,String i,String rarity,int col){slots.put(k,new S(t,i,rarity,col));invalidate();}
    protected void onDraw(Canvas c){hits.clear();int w=getWidth(),h=getHeight();p.setShader(new LinearGradient(0,0,0,h,Color.rgb(7,15,22),Color.rgb(4,9,14),Shader.TileMode.CLAMP));c.drawRoundRect(0,0,w,h,dp(18),dp(18),p);p.setShader(null);p.setShader(new RadialGradient(w*.5f,h*.43f,w*.36f,Color.argb(95,70,143,180),Color.TRANSPARENT,Shader.TileMode.CLAMP));c.drawCircle(w*.5f,h*.43f,w*.36f,p);p.setShader(null);if(hero!=null)c.drawBitmap(hero,null,new RectF(w*.20f,dp(18),w*.80f,h-dp(66)),p);
        String[] left={"head","weapon","chest","hands","legs","ring_left"},right={"neck","offhand","utility","belt","feet","ring_right"};float bw=Math.min(dp(130),w*.32f),bh=dp(48),y=dp(30);for(int i=0;i<left.length;i++){slot(c,left[i],dp(8),y,bw,bh);slot(c,right[i],w-bw-dp(8),y,bw,bh);y+=dp(56);}String[] rs={"relic_1","relic_2","relic_3","relic_4"};float gap=dp(5),rw=(w-dp(18)-gap*3)/4f,ry=h-dp(57);for(int i=0;i<4;i++)slot(c,rs[i],dp(9)+i*(rw+gap),ry,rw,dp(47));
        p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(Color.rgb(38,55,65));c.drawRoundRect(new RectF(.5f,.5f,w-.5f,h-.5f),dp(18),dp(18),p);p.setStyle(Paint.Style.FILL);
    }
    void slot(Canvas c,String k,float x,float y,float w,float h){S s=slots.get(k);boolean eq=s!=null&&s.item!=null&&!s.item.isEmpty();int col=eq?s.col:Color.rgb(60,77,85);RectF r=new RectF(x,y,x+w,y+h);hits.put(k,r);p.setColor(Color.argb(225,7,17,23));c.drawRoundRect(r,dp(10),dp(10),p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(eq?1.4f:1));p.setColor(col);c.drawRoundRect(r,dp(10),dp(10),p);p.setStyle(Paint.Style.FILL);if(eq){p.setColor(Color.argb(45,Color.red(col),Color.green(col),Color.blue(col)));c.drawCircle(x+dp(14),y+h/2,dp(10),p);glyphMini(c,s.item,x+dp(14),y+h/2,dp(7),col);}p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(dp(6.8f));p.setColor(col);c.drawText(fit((s==null?k:s.title).toUpperCase(Locale.ROOT),w-dp(eq?34:12)),x+dp(eq?28:6),y+dp(15),p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(dp(7.5f));p.setColor(eq?Color.rgb(238,237,229):Color.rgb(112,132,138));c.drawText(fit(eq?s.item:"Tuščia",w-dp(eq?34:12)),x+dp(eq?28:6),y+dp(34),p);}
    void glyphMini(Canvas c,String n,float x,float y,float r,int col){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1.2f));p.setColor(col);if(n.toLowerCase(Locale.ROOT).contains("edge")){c.drawLine(x-r,y+r,x+r,y-r,p);}else c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.FILL);}
    String fit(String s,float m){if(p.measureText(s)<=m)return s;String x=s;while(x.length()>2&&p.measureText(x+"…")>m)x=x.substring(0,x.length()-1);return x+"…";}
    public boolean onTouchEvent(MotionEvent e){if(e.getActionMasked()==MotionEvent.ACTION_UP)for(Map.Entry<String,RectF> q:hits.entrySet())if(q.getValue().contains(e.getX(),e.getY())){performClick();if(listener!=null)listener.onSlotPressed(q.getKey());return true;}return true;}public boolean performClick(){super.performClick();return true;}int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}


class NpcPortraitV070 extends View {
    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); String name="",role="";
    NpcPortraitV070(Context c){super(c);setLayerType(LAYER_TYPE_SOFTWARE,null);}
    void setNpc(String n,String r){name=n==null?"":n;role=r==null?"":r;invalidate();}
    protected void onDraw(Canvas c){
        float w=getWidth(),h=getHeight(),cx=w*.5f;int seed=Math.abs(name.hashCode());
        int ar=95+(seed%70),ag=92+((seed/7)%65),ab=78+((seed/13)%70);int accent=Color.rgb(ar,ag,ab);
        p.setShader(new LinearGradient(0,0,w,h,Color.rgb(11,22,29),Color.rgb(4,9,14),Shader.TileMode.CLAMP));c.drawRoundRect(0,0,w,h,Math.min(w,h)*.16f,Math.min(w,h)*.16f,p);p.setShader(null);
        p.setColor(Color.argb(70,Color.red(accent),Color.green(accent),Color.blue(accent)));c.drawCircle(cx,h*.37f,Math.min(w,h)*.42f,p);
        p.setColor(Color.rgb(20+(seed%18),27+((seed/5)%18),31+((seed/9)%20)));Path body=new Path();body.moveTo(w*.12f,h);body.quadTo(w*.20f,h*.68f,cx,h*.65f);body.quadTo(w*.80f,h*.68f,w*.88f,h);body.close();c.drawPath(body,p);
        p.setColor(Color.rgb(174+seed%34,142+(seed/3)%30,111+(seed/5)%25));c.drawRoundRect(w*.42f,h*.48f,w*.58f,h*.70f,w*.06f,w*.06f,p);c.drawOval(new RectF(w*.30f,h*.15f,w*.70f,h*.58f),p);
        p.setColor(Color.rgb(18+(seed%24),19+((seed/4)%23),19+((seed/8)%24)));Path hair=new Path();hair.moveTo(w*.27f,h*.39f);hair.quadTo(w*.28f,h*.08f,cx,h*.09f);hair.quadTo(w*.76f,h*.11f,w*.72f,h*.46f);hair.lineTo(w*.63f,h*.35f);hair.quadTo(w*.58f,h*.20f,w*.47f,h*.19f);hair.quadTo(w*.35f,h*.22f,w*.34f,h*.42f);hair.close();c.drawPath(hair,p);
        p.setColor(Color.rgb(216,224,211));c.drawCircle(w*.40f,h*.34f,Math.max(1,w*.018f),p);c.drawCircle(w*.60f,h*.34f,Math.max(1,w*.018f),p);
        p.setColor(Color.argb(120,80,53,40));p.setStrokeWidth(Math.max(1,w*.012f));c.drawLine(cx,h*.34f,cx-w*.018f,h*.43f,p);
        p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(1,w*.025f));p.setColor(accent);c.drawRoundRect(w*.05f,h*.05f,w*.95f,h*.95f,w*.14f,w*.14f,p);p.setStyle(Paint.Style.FILL);
    }
}
